Minor changes

diff --git a/add_full b/add_full
--- a/add_full
+++ b/add_full
@@ -1,6 +1,8 @@
 #!/usr/bin/env bash
-# NOTE: This file adds params that require the "full" data file
+#------------------------------------------------------------------------------#
+# This file adds params that require the "full" data file
 # NOTE: Need to add stuff to the base experiment!
+#------------------------------------------------------------------------------#
 # Call the file
 repair=./add_full.ncl
 case ${HOSTNAME%%.*} in
@@ -25,7 +27,9 @@ add() {
 
 # Loop
 pmax=18 # try to parallelize, really slow otherwise
-globs=('hs*t95l60e*') # add to every single file
+globs=('*t95l60e*')
+# globs=('*troprad3*p0020*')
+dayglob='3600'
 for glob in "${globs[@]}"; do
   for dir in $scratch/$glob; do
     echo "Dir: ${dir##*/}"
@@ -35,19 +39,21 @@ for glob in "${globs[@]}"; do
     i=0 # make sure to wait once we get here
     unset pids
     for full in ${filenames[@]}; do
-      let i+=1
-      echo "File: ${full##*/}"
-      summary=${full/full/summary}
-      ! [ -r $summary ] && echo "Error: Companion summary file ${summary##*/} not found." && continue
-      add &
-      pids+=($!)
-      if [ $((${#pids[@]} % pmax)) -eq 0 ] || [ $i -eq ${#filenames[@]} ]; then
-        for pid in ${pids[@]}; do
-          wait $pid
-          [ $? -eq 0 ] && echo "Error: One of the processes failed. Crap." && exit 1
-        done
-        echo "Elapsed time: $(($(date +%s) - t))s."
-        t=$(date +%s)
+      if [ -z "$dayglob" ] || [[ ${full##*/} =~ "$dayglob" ]]; then
+        let i+=1
+        echo "File: ${full##*/}"
+        summary=${full/full/summary}
+        ! [ -r $summary ] && echo "Error: Companion summary file ${summary##*/} not found." && continue
+        add &
+        pids+=($!)
+        if [ $((${#pids[@]} % pmax)) -eq 0 ] || [ $i -eq ${#filenames[@]} ]; then
+          for pid in ${pids[@]}; do
+            wait $pid
+            [ $? -eq 0 ] && echo "Error: One of the processes failed. Crap."
+          done
+          echo "Elapsed time: $(($(date +%s) - t))s."
+          t=$(date +%s)
+        fi
       fi
     done
   done
