Cleanup

diff --git a/compile b/compile
--- a/compile
+++ b/compile
@@ -2,6 +2,11 @@
 ################################################################################
 # Script for compiling fortran source code on various machines.
 ################################################################################
+# Raise error
+raise() {
+  echo "Error: $@" 1>&2
+  exit 1
+}
 # Variables
 # Maybe need -lmpl, -lmpichf90, -lmpl, -lm, -lz
 bin='./bin'
@@ -47,7 +52,7 @@ case ${HOSTNAME%%.*} in
     cpp=pgcc
     fflags='-Ktrap=fp'
     ldflags='-Mmpi=mpich'
-  ;; *) echo "Error: Unknown host, must configure library and binary locations before running." && exit 1 ;;
+  ;; *) raise "Unknown host, must configure library and binary locations before running." ;;
 esac
 
 # Directories
@@ -58,11 +63,11 @@ mkmftemplate=$root/bin/mkmf.template           # template of most basic settings
 mppnsource=$root/postprocessing/mppnccombine.c # source code
 # Make sure necessary things tools are in path
 ! [ -d $bin ]          && mkdir $bin || echo "Warning: Leaving old compiled source."
-! [ -d $src ]          && echo "Error: Could not find source code directory $src."        && exit 1
-! [ -r $pathnames ]    && echo "Error: Could not find path_names file $pathnames."        && exit 1
-! [ -r $mppnsource ]   && echo "Error: Could not find mppnccombine source code."          && exit 1
-! [ -r $mkmftemplate ] && echo "Error: Could not find Makefile template."          && exit 1
-! [ -r $mkmf ]         && echo "Error: Could not find Makefile-generating utility $mkmf." && exit 1
+! [ -d $src ]          && raise "Could not find source code directory $src."
+! [ -r $pathnames ]    && raise "Could not find path_names file $pathnames."
+! [ -r $mppnsource ]   && raise "Could not find mppnccombine source code."
+! [ -r $mkmftemplate ] && raise "Could not find Makefile template."
+! [ -r $mkmf ]         && raise "Could not find Makefile-generating utility $mkmf."
 
 #------------------------------------------------------------------------------
 # Build executable model code and post-processing tool
diff --git a/process_post b/process_post
--- a/process_post
+++ b/process_post
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-usage='process_post [OPTION...]'
+usage='process_post [OPTION...] GLOB1 [GLOB2 ...]'
 doc="This script processes the parallel-produced results of GFDL model runs,
 using saved pressure-level data.
 
@@ -7,11 +7,17 @@ Usage
 
   $usage
 
-Options
+Required arguments
 
-  -p=*  Number of parallel processes for splitting NetCDF files.
-  -i    Interpolate from pressure levels to isentropes in parallel.
-  -s    Calculate spectra in parallel.
+  GLOB1  The quoted glob pattern for experiment directories for which we
+         want to process data. 'full' files will be searched for in the
+         'netcdf' subdirectories of the experiment directories.
+
+Optional arguments
+
+  -p=*   Number of parallel processes for splitting NetCDF files.
+  -i     Interpolate from pressure levels to isentropes in parallel.
+  -s     Calculate spectra in parallel.
 "
 # Notes
 # * Feel free to add other random tasks, e.g. deleting dud variables
@@ -26,7 +32,12 @@ Options
 #   frequencies/wavenumbers use:
 #   ncvardump t 2xdaily_inst_spectral.d0500-d0600.nc | xargs
 #   ncvardump tvar 2xdaily_inst_full.d0500-d0600.nc | xargs
-################################################################################
+# Raise error
+raise() {
+  echo "Usage: $usage" 1>&2
+  echo "Error: $1" 1>&2
+  exit $2
+}
 # Initial stuff
 shopt -s nullglob
 cwd=$(pwd)
@@ -45,18 +56,18 @@ while [ $# -gt 0 ]; do
     -p=*) pmax=${1#*=} ;;
     -i) isen_parallel=true ;;
     -s) spectra_parallel=true ;;
-    -*) echo "Error: Unknown flag $1." && exit 1 ;;
+    -*) raise "Unknown flag $1." ;;
     *)  globs+=("$1") ;;
   esac
   shift
 done
-[ -z "$pmax" ] && echo "Error: Must specify parallelization." && exit 1
+[ -z "$pmax" ] && raise "Must specify parallelization."
 
 # Files and experiment folders over which we iterate
 case ${HOSTNAME%%.*} in
   monde*)    scratches=(/mdata1/ldavis /mdata2/ldavis) ;; # mdata1 has t42l20s
   cheyenne*) scratches=/glade/scratch/davislu ;;
-  *) echo "Error: Unknown host, must edit batch script before continuing." && exit 1 ;;
+  *) raise "Unknown host, must edit batch script before continuing." ;;
 esac
 
 #------------------------------------------------------------------------------#
@@ -91,7 +102,7 @@ background() {
   for j in $(seq 1 $npids); do
     wait ${pids[j-1]}
     logcheck ${logs[j-1]}
-    [ $? -ne 0 ] && echo "Error: One of the processes failed. Crap." && exit 1
+    [ $? -ne 0 ] && raise "One of the processes failed. Crap."
   done
   echo "Elapsed time: $(($(date +%s) - t))s."
 }
