Isentropic interpolation inline

diff --git a/drycore_run b/drycore_run
--- a/drycore_run
+++ b/drycore_run
@@ -29,7 +29,7 @@ tend=0
 run=mpirun # for running in parallel
 fms=$cwd/fms.x # location of executables
 process=$cwd/process # *process the parallel-output nc files directly before merging*
-interp_ncl=$cwd/process_interp.ncl # we direclty invoke this sometimes
+interp=$cwd/pressure_interp.ncl # for forcing data
 [ ! -x $fms ]     && echo "Error: The executable $fms is missing."                 && exit 1
 [ ! -x $process ] && echo "Error: The bash script for processing data is missing." && exit 1
 ! which $run &>/dev/null && echo "Error: $run not found in \$PATH." && exit 1
@@ -112,9 +112,9 @@ exit_check() {
     echo "Error: Exit status $estatus from post-processing previous block..."
     case $estatus in
       1) echo "NetCDF files missing. Check log.model." ;;
-      2) echo "Something failed during pressure level interpolation. Check log.interp." ;;
-      3) echo "Something failed while getting basic terms. Check log.means." ;;
-      4) echo "Something failed while getting param terms. Check log.params." ;;
+      2) echo "Something failed during plev or isen interpolation. Check log.process." ;;
+      3) echo "Something failed while getting plev zonal means. Check log.process." ;;
+      4) echo "Something failed while getting plev or isen params. Check log.process." ;;
       *) echo "Check log.process; other/miscellaneous failure." ;;
     esac
     exit 1
@@ -324,13 +324,15 @@ egrep 'EXIT CODE: [1-9]|FATAL from PE|WARNING from PE' log.model &>/dev/null && 
 # NOTE: The boundary layer stuff depends on sigma, which depends on the surface
 # pressure, a boundary layer quantity... but we assume effect is negligible
 # when terrain is zero. So ignore it.
-ncrename -h -d pfull,mlev -d phalf,ilev forcing.nc &>/dev/null # mlev is the ECHAM convention, needed for CDO interpolation
-ncrename -h -v pfull,mlev -v phalf,ilev forcing.nc &>/dev/null # -d renames dimensions, -v renames variables of same name
+ncrename -h -d pfull,mlev forcing.nc
+ncrename -h -d phalf,ilev forcing.nc
+ncrename -h -v pfull,mlev forcing.nc
+ncrename -h -v phalf,ilev forcing.nc
 ncatted -h -O -a bounds,mlev,o,c,"ilev" forcing.nc
 [ -r ../forcing.nc ] && rm ../forcing.nc
-ncl -n -Q 'filename="forcing.nc"' 'output="../forcing.nc"' $interp_ncl &>forcing.log
+ncl -n -Q 'filename="forcing.nc"' 'output="../forcing.nc"' $interp &>forcing.log
 if nclcheck forcing.log || ! [ -r ../forcing.nc ]; then
-  echo "Error: Something failed during NCL interpolation." && exit 1
+  echo "Error: Something failed during NCL interpolation of forcin gdata." && exit 1
 fi
 # Exit if user *only* wanted to get initial conditions
 $forcing && exit 0
@@ -356,6 +358,7 @@ case $mode in
     # Message and reset timer/flagS
     # Skip this time (optionally)
     if [ $cday -lt $tstart ]; then
+      unset rdir_override # important! for 'resume' experiments, generally just want to use rdir_override as cold start alternative
       pday=$cday # previous day
       cday=$((pday + days))
       nday=$((cday + days))
@@ -367,15 +370,17 @@ case $mode in
     # Optionally use the end of other control runs to reduce spinup time
     rdir=$expdir/d$(printf "%04d" $pday)-d$(printf "%04d" $cday)
     cdir=$expdir/d$(printf "%04d" $cday)-d$(printf "%04d" $nday)
-    if [ ! -z $rdir_override ]; then coldstart=false
-      if [[ ! $rdir_override =~ d.*-d.* ]]; then
+    if [ -n "$rdir_override" ]; then
+      coldstart=false
+      if ! [[ $rdir_override =~ d.*-d.* ]]; then
         echo "Override: Using final day from \"$rdir_override\" for restart files."
         rdir_override=($rdir_override/d*-d*); rdir="${rdir_override[-1]}" # pick last one; should be sorted
       else
         echo "Override: Using restart files from \"$rdir_override\"."
         rdir="$rdir_override" # use specific day sequence
-      fi; unset rdir_override # only ever use this on first 'day' of a new experiment; for subsequent days, continue from earlier day block
-      [ ! -d $rdir ] && echo "Error: Override restart directory \"$rdir\" does not exist." && exit 1
+      fi
+      unset rdir_override # only ever use this on first 'day' of a new experiment; for subsequent days, continue from earlier day block
+      ! [ -d $rdir ] && echo "Error: Override restart directory \"$rdir\" does not exist." && exit 1
     fi
     unset pflags_day
     array_in $cday ${t_nodata[@]} && pflags_day+=" -q" && echo "Will delete output netcdf files."
diff --git a/drycore_series b/drycore_series
--- a/drycore_series
+++ b/drycore_series
@@ -88,7 +88,7 @@ filename=2xdaily_inst # name for output files
 ktstart=3500 # first day we keep XYZ data (can't keep all, too much data)
 ktend=5500 # last day we keep XYZ data
 # Test settings
-testmode=0
+testmode=false
 testname=test # default name of directory
 initname=init
 testdays=5
@@ -103,7 +103,7 @@ unset series_name flags_global
 while [ $# -gt 0 ]; do # echo "Flag: $1"
   case "$1" in
     -h|--help) echo "$doc" && exit 0 ;;
-    -t|--test) testmode=1 ;;
+    -t|--test) testmode=true ;;
     -d|--dryrun) dryrun=true ;; # just print function calls?
     -dt=*|--timestep=*) dt=${1#*=} ;;
     -d=*|--days=*)      days=${1#*=} ;;
@@ -143,16 +143,14 @@ reso="${reso#*_}"
 reso="${reso%%_*}"
 
 # Run really fast test run
-case $testmode in
-1)
+if $testmode; then
   unset flags_global # no resume or new days
-  rdir="${force}_base_t95l60e" # override previous directory
-  rdays=d0450-d0500 # set restart directory days (leave empty to just use the last subfolder in directory)
-  pflags+=" -d" # don't move/delete anything; also implies flags="--keep-xyz "
+  # rdir="${force}_base_t95l60e" # override previous directory
+  # rdays=d0450-d0500 # set restart directory days (leave empty to just use the last subfolder in directory)
+  # pflags+=" -d" # don't move/delete anything; also implies flags="--keep-xyz "
   outfreq=12
   frequnits=hours
   filename=test
-  dt=600
   days=$testdays
   tstart=0
   tend=$((testdays * testblocks))
@@ -160,21 +158,7 @@ case $testmode in
   ktend=$tend
   walltime=01:00 # real quick test
   queue=regular
-# Initial conditions, for sanity checks
-;; 2)
-  unset flags_global # no resume or new days
-  cores=1 # easier for debugging, otherwise print statements executed simultaneously
-  pflags+=" -q" # do nothing
-  outfreq=1
-  frequnits=seconds
-  filename=init
-  dt=1
-  days=0
-  secs=1
-  tstart=0
-  tend=0
-  queue=priority
-;; esac
+fi
 # Days for keeping
 txyzdata=$(seq $ktstart $days $ktend | tr $'\n' ',') # for saving
 
@@ -215,6 +199,12 @@ cp $bindir/mppnccombine.x ./ # location of executables
 #------------------------------------------------------------------------------#
 # Helper functions
 #------------------------------------------------------------------------------#
+# Helper
+err() {
+  echo $@ 1>&2
+  exit 1
+}
+
 # Array membership
 array_in() {
   [[ " ${@:2} " =~ " ${1} " ]]
@@ -228,7 +218,7 @@ array_in() {
 array_add() {
   while [ $# -ne 0 ]; do
     if [ -n "$2" ] && [ "${#2}" -gt 1 ] && [ "$2" != "v-" ] && [ "$2" != "v''" ]; then
-      [ "${2:0:1}" != v ] && echo "Error: Values must be input as v<value>." 1>&2 && exit 1
+      [ "${2:0:1}" != v ] && err "Error: Values must be input as v<value>."
       nml_params+=("$1")
       nml_values+=("${2#v}")
     fi
@@ -257,8 +247,7 @@ exp_name() {
   # Detect whether this is a 'base' experiment. Experiment series can
   # 'intersect' each other, and this ensures we aren't duplicating model runs
   if [ -n "$rparam1" ] && [ -n "$rparam2" ]; then
-    echo "Error: Cannot do 'diagonal' continuation experiments." 1>&2
-    exit 1
+    err "Error: Cannot do 'diagonal' continuation experiments."
   fi
   # This loop will be through only 1 or 2 params, since we enforce at least
   # rparam1 or rparam2 are empty. Idea is restarts should be taken from the
@@ -323,8 +312,7 @@ exp_name() {
           [[ $p2 == 1 ]] && sweep_out=katmos$opt p2=
           ;;
         *)
-          echo "Error: Unknwon experiment \"${sweep_in}\"."
-          exit 1
+          err "Error: Unknwon experiment \"${sweep_in}\"."
           ;;
       esac
       [ "$p1" == na ] && unset p1
@@ -390,20 +378,19 @@ exp_setup() {
       ktrop=-${p_values[0]}
       if [[ $exp_sweep =~ katmos[123]-kfric ]]; then
         kfric=-${p_values[1]} # diagaonal experiment
-        [ -z "$kfric" ] && echo "Error: Need second param for diagonal experiment." && exit 1
+        [ -z "$kfric" ] && err "Error: Need second param for diagonal experiment."
       elif [[ $exp_sweep =~ katmos[123]-tgrad ]]; then
         delh=${p_values[1]} # diagaonal experiment
-        [ -z "$delh" ] && echo "Error: Need second param for diagonal experiment." && exit 1
+        [ -z "$delh" ] && err "Error: Need second param for diagonal experiment."
       elif [[ $exp_sweep =~ katmos[123]-tshift ]]; then
         exph=${p_values[1]} # diagaonal experiment
-        [ -z "$exph" ] && echo "Error: Need second param for diagonal experiment." && exit 1
+        [ -z "$exph" ] && err "Error: Need second param for diagonal experiment."
       elif [ "$suffix" == anom ]; then
         ktrop="-40,$ktrop"
       elif [ "$suffix" == mean ]; then
         ktrop="$ktrop,-40"
       elif [ "$suffix" != fixed ] && [ "$suffix" != "$exp_sweep" ]; then
-        echo "Error: Unknown suffix option ${suffix}." 1>&2
-        exit 1
+        err "Error: Unknown suffix option ${suffix}."
       fi
       kstrat=$ktrop # if hs forcing, will not change anything
       kmeso=$ktrop
@@ -415,9 +402,7 @@ exp_setup() {
           [01]) ikbl=-4 ;; # hold boundary layer value constant
           2) ikbl=-$(bc -l <<< "scale=3; ${iktrop#-}/10") ;; # hold ratio constant; i.e. keep it at 10
           3) ikbl=-$(bc -l <<< "scale=3; (4^-1 + (${iktrop#-}^-1 - 40^-1))^-1") ;; # preserve 'boundary layer' component
-          *)
-            echo "Error: Unknown blopt ${blopt}." 1>&2
-            exit 1 ;;
+          *) err "Error: Unknown blopt ${blopt}." ;;
         esac
         kbl=$kbl,$ikbl # mean and anomaly components
       done
@@ -436,8 +421,7 @@ exp_setup() {
       kstrat=-${p_values[0]}
       kdepth=${p_values[1]} # param 2 is depth of transition region
       if [ -z "$kdepth" ]; then
-        echo "Error: Need to specify transition depth as second parameter." 1>&2
-        exit 1
+        err "Error: Need to specify transition depth as second parameter."
       fi
       stratdamp=${prefix##*[0-9]}
       if [ "$stratdamp" == 0 ]; then
@@ -445,8 +429,7 @@ exp_setup() {
       elif [ "$stratdamp" == 1 ]; then
         stratdamp=linear
       else
-        echo "Error: Unknown stratosphere damping option ${stratdamp}." 1>&2
-        exit 1
+        err "Error: Unknown stratosphere damping option ${stratdamp}."
       fi
       # Detect other options
       if [ "$suffix" == anom ]; then
@@ -456,13 +439,11 @@ exp_setup() {
       elif [ "$suffix" == mean ]; then
         kstrat="$kstrat,-40"
       elif [ -n "$suffix" ]; then
-        echo "Error: Unknown suffix option ${suffix}." 1>&2
-        exit 1
+        err "Error: Unknown suffix option ${suffix}."
       fi
 
     # Unknown
-    ;; *) echo "Error: Unknown experiment series \"$exp_sweep\"." 1>&2
-          exit 1
+    ;; *) err "Error: Unknown experiment series \"$exp_sweep\"."
   ;; esac
 
   #----------------------------------------------------------------------------#
@@ -486,8 +467,7 @@ exp_setup() {
     95)  nlat=144 ;; # for 36-core Cheyenne nodes
     106) nlat=160 ;;
     170) nlat=256 ;;
-    *) echo "Error: Invalid truncation number \"$ntrunc\"." 1>&2
-       exit 1 ;;
+    *)   err "Error: Invalid truncation number \"$ntrunc\"." ;;
   esac
   nsphere=$(($ntrunc + 1)) # forget what difference between num fourier and num spherical means
   nlon=$(($nlat * 2)) # always twice the res
@@ -499,8 +479,7 @@ exp_setup() {
     *e) coord=input;      nlev=60;        levels=$f90dir/levels_era.nml ;; # ERA-Interim coordinates
     *p) coord=pk_sigma;   nlev=${vert%p}; levels= ;;
     *s) coord=even_sigma; nlev=${vert%s}; levels= ;;
-    *) echo "Error: Unknown vertical coordinate identifier \"${vert}\"." 1>&2
-       exit 1 ;;
+    *)  err "Error: Unknown vertical coordinate identifier \"${vert}\"." ;;
   esac
   array_add num_levels v$nlev vert_coord_option v\'$coord\'
 
@@ -559,7 +538,8 @@ exp_setup() {
   # Set up diag table; so far this is kept very simple
   #------------------------------------------------------------------------#
   diag="$exp_dir/diag_table"
-  [ $testmode -eq 2 ] && diag_default=$f90dir/diag_table_init || diag_default=$f90dir/$diag_table
+  # $testmode  && diag_default=$f90dir/diag_table_init || diag_default=$f90dir/$diag_table
+  diag_default=$f90dir/$diag_table
   cp $diag_default $diag
   sed -i 's/filename/"'$filename'"/g;s/outfreq/'$outfreq'/g;s/frequnits/"'$frequnits'"/g' $diag
   sed -i 's/#.*$//g;/^[ \t]*$/d' $diag # remove comments, empty lines, for clarity
@@ -605,12 +585,12 @@ for param2 in ${params2[@]}; do
       continue
     fi
     exp_names+=($exp_name) # record in list
-    case $testmode in
-      0) exp_dir="$scratch/$exp_name" ;; # running model
-      1) exp_dir="$scratch/$testname" ;;
-      2) exp_dir="$scratch/$initname" ;;
-    esac
-    [ ! -d "$exp_dir" ] && mkdir "$exp_dir"
+    if $testmode; then
+      exp_dir="$scratch/$testname"
+    else
+      exp_dir="$scratch/$exp_name"
+    fi
+    ! [ -d "$exp_dir" ] && mkdir "$exp_dir"
     log=logs/${exp_dir##*/}.log # e.g use the testing name
     echo "Experiment name: ${exp_name}." | tee $log
     echo "Log file: log $log" # so can copy paste this
