In process of creating "minimal" run scripts.

diff --git a/drycore_run b/drycore_run
--- a/drycore_run
+++ b/drycore_run
@@ -15,12 +15,12 @@ if [ -z $DAYS ] || [ -z $DT ] || [ -z $LEV ] || [ -z $NTRUNC ] \
   || [ -z $KF ] || [ -z $KA ] || [ -z $KS ] || [ -z $KT ] \
   || [ -z $EXPNAME ] || [ -z $EXPTYPE ] || [ -z $FILENAME ] || [ -z $EXPDIR ] \
   || [ -z $SPINDOWN ] || [ -z $CONTROL ]; then
-  echo "ERROR: Required variable was not set in batch script."
+  echo "Error: Required variable was not set in batch script."
   exit 1
 fi
 # Experiment naming for storage
 if [ "$EXPNAME" != "hs" ] && [ "$EXPNAME" != "pk" ]; then
-  echo "ERROR: Unknown experiment type ${EXPNAME}."
+  echo "Error: Unknown experiment type ${EXPNAME}."
   exit 1
 fi
 # Vertical resolution options
@@ -31,7 +31,7 @@ elif [[ "$LEV" =~ ^[0-9]+$ ]]; then
   COORD=even_sigma # even pressure spacing
   NLEVS="$LEV" # levels variable should just encode number desired
 else
-  echo "ERROR: Unknown vertical coordinate identifier ${LEV}."
+  echo "Error: Unknown vertical coordinate identifier ${LEV}."
   exit 1
 fi
 # Horizontal coordinates
@@ -39,7 +39,7 @@ case $NTRUNC in
   42) NLATS=64 ;;
   63) NLATS=96 ;;
   85) NLATS=128 ;;
-  *) echo "ERROR: Invalid number of cores."; exit 1 ;;
+  *) echo "Error: Invalid number of cores."; exit 1 ;;
 esac
 # Optional topography file (if exists will get copied into INPUT folders)
 [[ -r $TOPOFILE ]] && TOPO=input || TOPO=flat # if name empty then [] will yield true
@@ -62,29 +62,29 @@ elif [ "$hostname" == "monde" ]; then
   scratch=/mdata1/ldavis
   storage=/home/ldavis
 else
-  echo "ERROR: Unknown host, must configure library and binary locations before running."
+  echo "Error: Unknown host, must configure library and binary locations before running."
   exit 1
 fi
 # Executable check
-fms=$PWD/${hostname}_${EXPNAME}/fms.x # location of executables
-process=$PWD/process # the script for on-the-fly processing
-postprocess=$PWD/postprocess # the script for post-processing
+fms=$PWD/exe_${EXPNAME}_${hostname}/fms.x # location of executables
+process=$PWD/process                      # the script for on-the-fly processing
+postprocess=$PWD/postprocess              # the script for post-processing
 if [ ! -x $fms ]; then # x for 'executable'
-  echo "ERROR: The executable $fms is missing."
+  echo "Error: The executable $fms is missing."
   exit 1
 fi
 if [ ! -x $process ]; then
-  echo "ERROR: The bash script for processing data is missing."
+  echo "Error: The bash script for processing data is missing."
   exit 1
 fi
 if [ ! -x $postprocess ]; then
-  echo "ERROR: The bash script for post-processing data is missing."
+  echo "Error: The bash script for post-processing data is missing."
   exit 1
 fi
 # Base directory for experiment run
 # Optionally exit from script if directory already exists
 basedir=$scratch/$EXPDIR # helper
-[ ! -z $NEWEXPER ] && $NEWEXPER && [ -d $basedir ] && echo "ERROR: Working directory already exists. Continuing..." && exit 1
+[ ! -z $NEWEXPER ] && $NEWEXPER && [ -d $basedir ] && echo "Error: Working directory already exists. Continuing..." && exit 1
 [ ! -d $basedir ] && mkdir $basedir # make directory
 
 ################################################################################
@@ -99,11 +99,11 @@ function Setup() {
   cdir=$1
   ncrecord=$2
   if [ -z $1 ] || [ -z $2 ]; then
-    echo "ERROR: Not enough arguments provided to Setup() function."
+    echo "Error: Not enough arguments provided to Setup() function."
     exit 1
   fi
   if [ -z $radiationoff ] || [ -z $frictionoff ] || [ -z $surfaceoff ]; then
-    echo "ERROR: Required environmental variable not set."
+    echo "Error: Required environmental variable not set."
     exit 1
   fi
   # Set up working directory, and move there
@@ -438,10 +438,10 @@ EOF
 # Take one argument: directory where restart files exist
 function Restart() {
   rdir=$1 # the restart direcotry
-  [ ! -d $rdir ] && echo "ERROR: Restart directory $rdir does not exist." && exit 1
+  [ ! -d $rdir ] && echo "Error: Restart directory $rdir does not exist." && exit 1
   # Copy over relevant restart files for exp type; if missing, raise error
   if [ -z $1 ]; then
-    echo "ERROR: Not enough arguments provided to Restart() function."
+    echo "Error: Not enough arguments provided to Restart() function."
     exit 1
   fi
   if [ "$EXPTYPE" == "spectral" ]; then
@@ -454,7 +454,7 @@ function Restart() {
   echo "Moving restart files from ${rdir##*/}/RESTART to ${PWD##*/}/INPUT..."
   for file in ${resfiles[@]}; do
     if [ ! -r $rdir/RESTART/$file ]; then
-      echo "ERROR: Missing restart file ${rdir##*/}/RESTART/${file}."
+      echo "Error: Missing restart file ${rdir##*/}/RESTART/${file}."
       exit 1
     else
       cp $rdir/RESTART/$file INPUT/$file
@@ -471,7 +471,7 @@ function Iterate() {
   ncrecord=$1
   nckeep=$2
   if [ -z $1 ] || [ -z $2 ]; then
-    echo "ERROR: Not enough arguments provided to Iterate() function."
+    echo "Error: Not enough arguments provided to Iterate() function."
     exit 1
   fi
   start=$(date +%s)
@@ -486,7 +486,7 @@ function Iterate() {
   if [ ! -z $p2 ]; then
     wait $p2; estatus=$? # wait command will always exit with exit status of supplied process ID
     if [ $estatus != 0 ]; then
-      echo "ERROR: Exit status $estatus from previous model step..."
+      echo "Error: Exit status $estatus from previous model step..."
       case $estatus in
         1) echo "Something failed during model integration. Check log.model." ;;
         2) echo "Something failed during model interpolation. Check log.interp." ;;
@@ -532,7 +532,7 @@ estatus=0 # initialize exit status
 if $CONTROL; then
   # CHECK THAT TIMING VARIABLES ARE DECLARED
   if [ -z $TSTART ] || [ -z $TEND ] || [ -z $TKEEP ] || [ -z $TRECORD ]; then
-    echo "ERROR: One or more of the timing variables was not set."
+    echo "Error: One or more of the timing variables was not set."
     exit 1
   fi
   # PREPARE FOR THE LOOP
@@ -586,7 +586,7 @@ if $SPINDOWN; then
   # CHECK THAT TIMING VARIABLES ARE DECLARED
   if [ -z $TCONTROL ] || [ -z $TSPINSTART ] || [ -z $TSPINEND ] || [ -z $TSPINRECORD ] || [ -z $TSPINKEEP ]; then
     # echo TCONTROL $TCONTROL TSPINSTART $TSPINSTART TSPINEND $TSPINEND TSPINRECORD $TSPINRECORD TSPINKEEP $TSPINKEEP
-    echo "ERROR: One or more of the timing variables was not set."
+    echo "Error: One or more of the timing variables was not set."
     exit 1
   fi
   # PREPARE FOR THE LOOP
@@ -595,7 +595,7 @@ if $SPINDOWN; then
     2) radiationoff=true surfaceoff=false frictionoff=false ;;
     3) radiationoff=true surfaceoff=true frictionoff=true ;;
     4) radiationoff=false surfaceoff=false frictionoff=true ;;
-    *) echo "ERROR: Unknown spindown identifier \"$SPINDOWNOPT\"."; exit 1 ;;
+    *) echo "Error: Unknown spindown identifier \"$SPINDOWNOPT\"."; exit 1 ;;
   esac
   $radiationoff && radiation=off || radiation=on
   $surfaceoff && surface=off || surface=on
diff --git a/process b/process
--- a/process
+++ b/process
@@ -29,7 +29,7 @@ testing=$2          # check if testing mode enabled; if true, keep all intermedi
 basedir=${0%/*}     # same location as this file; trim filename from right
 interpwithcdo=false # interpolate with CDO instead of NCL? much slower during testing (see notes)
 hostname=${HOSTNAME%%.*} # trim e.g. monde.atmos.colostate.edu --> monde
-mppnccombine=$basedir/${hostname}_mppnccombine # combine; needs to have been compiled here
+mppnccombine=$basedir/mppnccombine # combine; needs to have been compiled here
 interpcdo=$basedir/process_interp     # interpolate with CDO
 interpncl=$basedir/process_interp.ncl # interpolate with NCL, automatic iteration
 # interpncl=$basedir/process_interpex.ncl # interpolate with NCL, explicitly interpolate select variables
@@ -40,39 +40,39 @@ lorenz=$basedir/process_energy.ncl  # eddy and mean Lorenz energy cycle terms wi
 # energy=$basedir/process_energy    # Lorenz energy cycle terms with CDO
 # Double check some stuff
 if [ -z "$nckeep" ]; then
-  echo "ERROR: Must pass bash true/false whether you want to keep original longitude-res data."
+  echo "Error: Must pass bash true/false whether you want to keep original longitude-res data."
   exit 999
 fi
 if [ -z "$testing" ]; then
-  echo "ERROR: Must pass bash true/false whether you want to use testing mode."
+  echo "Error: Must pass bash true/false whether you want to use testing mode."
   exit 999
 fi
 if ! hash ncl 2>/dev/null; then
-  echo "ERROR: NCL is not in $PATH."
+  echo "Error: NCL is not in $PATH."
   exit 999
 fi
 if ! hash cdo 2>/dev/null; then
-  echo "ERROR: CDO is not in $PATH."
+  echo "Error: CDO is not in $PATH."
   exit 999
 fi
 if ! hash ncrename 2>/dev/null || ! hash ncks 2>/dev/null; then
-  echo "ERROR: NCO is not in $PATH."
+  echo "Error: NCO is not in $PATH."
   exit 999
 fi
 if [ ! -x $mppnccombine ]; then
-  echo "ERROR: The mpp combine executable $mppnccombine is missing."
+  echo "Error: The mpp combine executable $mppnccombine is missing."
   exit 999
 fi
 if [ ! -x $basics ]; then
-  echo "ERROR: The script $basics is missing."
+  echo "Error: The script $basics is missing."
   exit 999
 fi
 if [ ! -x $lorenz ]; then
-  echo "ERROR: The script $lorenz is missing."
+  echo "Error: The script $lorenz is missing."
   exit 999
 fi
 if [ ! -r $interpncl ]; then
-  echo "ERROR: The script $interpncl is missing."
+  echo "Error: The script $interpncl is missing."
   exit 999
 fi
 
@@ -85,7 +85,7 @@ fi
 t=$(date +%s)
 for ncfile in *.nc.0000; do
   if [ "$ncfile" == "*.nc.0000" ]; then # make sure nullglob turned off
-    echo "ERROR: No output netcdf files found."
+    echo "Error: No output netcdf files found."
     exit 1 # tell invoking shell that previous model failed
   fi # then combine, if any exist
   files=(${ncfile%%.*}.nc*) # put into array
@@ -130,14 +130,14 @@ for ncfile in *.nc; do
   if $interpwithcdo; then
     echo "Interpolating with CDO..."
     $interpcdo $ncfile $interpfile &>log.interp # that simple babe
-    [ $? != 0 ] && echo "ERROR: Something failed during CDO interpolation." && exit $?
+    [ $? != 0 ] && echo "Error: Something failed during CDO interpolation." && exit $?
     ! $testing && rm interp?.nc
   # b) Use NCL vint2hp_ecmwf for interpolation
   else
     echo "Interpolating with NCL..." # -Q = no banner, -n = do not enumerate print statements
     ncl -n -Q "filename=\"$ncfile\"" "outfile=\"$interpfile\"" $interpncl &>log.interp #2> /dev/null
     if nclcheck log.interp || [ ! -r $interpfile ]; then
-      echo "ERROR: Something failed during NCL interpolation." && exit 2
+      echo "Error: Something failed during NCL interpolation." && exit 2
     fi
   fi
   # Standardize attributes
@@ -155,7 +155,7 @@ for ncfile in *.nc; do
   # echo "Getting extra parameters with NCL..." # -Q = no banner, -n = do not enumerate print statements
   # ncl -n -Q "filename=\"$ncfile\"" $params &>log.params #2> /dev/null
   # if nclcheck log.params; then
-  #   echo "ERROR: Something failed getting extra parameters with NCL." && exit 3
+  #   echo "Error: Something failed getting extra parameters with NCL." && exit 3
   # fi
   # echo "  * Time for getting extra parameters with NCL: $(($(date +%s) - $t))s."
 
@@ -167,7 +167,7 @@ for ncfile in *.nc; do
   echo "Getting basic terms..."
   $basics $ncfile &>log.basic &
   pbasics=$!
-  # [ $? != 0 ] && echo "ERROR: Something failed while getting basic terms." && exit 3
+  # [ $? != 0 ] && echo "Error: Something failed while getting basic terms." && exit 3
   # echo "  * Time for getting basic terms with CDO: $(($(date +%s) - $t))s."
   ##############################################################################
   # 3) Get energy terms in another file
@@ -178,20 +178,20 @@ for ncfile in *.nc; do
   ncl -n -Q "filename=\"$ncfile\"" $lorenz &>log.lorenz &
   plorenz=$!
   # if nclcheck log.lorenz; then
-  #   echo "ERROR: Something failed getting extra parameters with NCL." && exit 4
+  #   echo "Error: Something failed getting extra parameters with NCL." && exit 4
   # fi
   # echo "  * Time for getting Lorenz energy terms with NCL: $(($(date +%s) - $t))s."
   ##############################################################################
   # Manage background processes
   # First the basic term
   wait $pbasics # wait for basic terms
-  [ $? != 0 ] && echo "ERROR: Something failed while getting basic terms." && exit 3
+  [ $? != 0 ] && echo "Error: Something failed while getting basic terms." && exit 3
   twait=$(tail -1 log.basic | sed 's/[^0-9]*//g')
   echo "  * Time for getting basic terms with CDO: ${twait}s."
   # Next the Lorenz terms
   wait $plorenz # wait for Lorenz terms
   if nclcheck log.lorenz; then
-    echo "ERROR: Something failed getting extra parameters with NCL." && exit 4
+    echo "Error: Something failed getting extra parameters with NCL." && exit 4
   fi
   twait=$(tail -1 log.lorenz | sed 's/[^0-9]*//g')
   echo "  * Time for getting Lorenz energy terms with NCL: ${twait}s."
diff --git a/simple_run b/simple_run
--- a/simple_run
+++ b/simple_run
@@ -8,21 +8,18 @@ ulimit -s unlimited # set max open files
 
 # Check for testing; if true, then will keep all files in processing steps
 # This parameter is passed as argument to processing function
-[ -z $TESTING ] && testing=false || testing=$TESTING
-# Double check that everything was declared properly in the batch script
-# echo $DAYS $DT $LEV $NTRUNC $KF $KA $KS $KT $EXPNAME $EXPTYPE $FILENAME $SPINDOWN $CONTROL
-if [ -z $DAYS ] || [ -z $DT ] || [ -z $LEV ] || [ -z $NTRUNC ] \
-  || [ -z $KF ] || [ -z $KA ] || [ -z $KS ] || [ -z $KT ] \
-  || [ -z $EXPNAME ] || [ -z $EXPTYPE ] || [ -z $FILENAME ] || [ -z $EXPDIR ] \
-  || [ -z $SPINDOWN ] || [ -z $CONTROL ]; then
-  echo "ERROR: Required variable was not set in batch script."
-  exit 1
-fi
-# Experiment naming for storage
-if [ "$EXPNAME" != "hs" ] && [ "$EXPNAME" != "pk" ]; then
-  echo "ERROR: Unknown experiment type ${EXPNAME}."
-  exit 1
-fi
+DT=600 # time step in seconds
+DAYS=100 # days
+NTRUNC=42 # turncation number
+LEV=40
+EXPNAME=hs # input file and diag table will be in format input_$EXPNAME.nml
+TESTING=false
+EXPTYPE=spectral # one of "spectral", "fv", or "bgrid"
+TOPOFILE=
+
+# Optional topography file (if exists will get copied into INPUT folders)
+[[ -r $TOPOFILE ]] && TOPO=input || TOPO=flat # if name empty then [] will yield true
+
 # Vertical resolution options
 if [ "$LEV" == "jer" ] || [ "$LEV" == "era" ]; then # Jeremiah's input coordinates
   COORD=input # add a group to input.nml
@@ -31,79 +28,61 @@ elif [[ "$LEV" =~ ^[0-9]+$ ]]; then
   COORD=even_sigma # even pressure spacing
   NLEVS="$LEV" # levels variable should just encode number desired
 else
-  echo "ERROR: Unknown vertical coordinate identifier ${LEV}."
+  echo "Error: Unknown vertical coordinate identifier ${LEV}."
   exit 1
 fi
-# Horizontal coordinates
+
+# Horizontal resolution options
 case $NTRUNC in
   42) NLATS=64 ;;
   63) NLATS=96 ;;
   85) NLATS=128 ;;
-  *) echo "ERROR: Invalid number of cores."; exit 1 ;;
+  *) echo "Error: Invalid number of cores."; exit 1 ;;
 esac
-# Optional topography file (if exists will get copied into INPUT folders)
-[[ -r $TOPOFILE ]] && TOPO=input || TOPO=flat # if name empty then [] will yield true
+
 # Storage information
 hostname=${HOSTNAME%%.*} # monde is monde.atmos.colostate.edu
-if [ "$hostname" == "olbers" ]; then
-  mpirun=/usr/local/mpich3/bin/mpirun
-  scratch=/home/ldavis # no good place on this server
-  storage=/home/ldavis
-elif [ "$hostname" == "gauss" ]; then
-  mpirun=/usr/local/mpich3-pgi/bin/mpirun
-  scratch=/birner-scratch/ldavis # need to use special scratch directory
-  storage=/home/ldavis
-elif [ "$hostname" == "euclid" ]; then # everything is in same lib/bin
-  mpirun=/usr/local/bin/mpirun
-  scratch=/home/ldavis # not mounted, so plenty of space
-  storage=/birner-home/ldavis
-elif [ "$hostname" == "monde" ]; then
+if [ "$hostname" == "monde" ]; then
   mpirun=/usr/lib64/mpich/bin/mpirun
   scratch=/mdata1/ldavis
   storage=/home/ldavis
 else
-  echo "ERROR: Unknown host, must configure library and binary locations before running."
+  echo "Error: Unknown host, must configure library and binary locations before running."
   exit 1
 fi
+
 # Executable check
-fms=$PWD/${hostname}_${EXPNAME}/fms.x # location of executables
+fms=$PWD/exe_${EXPNAME}_${hostname}/fms.x # location of executables
 process=$PWD/process # the script for on-the-fly processing
 postprocess=$PWD/postprocess # the script for post-processing
 if [ ! -x $fms ]; then # x for 'executable'
-  echo "ERROR: The executable $fms is missing."
+  echo "Error: The executable $fms is missing."
   exit 1
 fi
 if [ ! -x $process ]; then
-  echo "ERROR: The bash script for processing data is missing."
+  echo "Error: The bash script for processing data is missing."
   exit 1
 fi
 if [ ! -x $postprocess ]; then
-  echo "ERROR: The bash script for post-processing data is missing."
+  echo "Error: The bash script for post-processing data is missing."
   exit 1
 fi
+
 # Base directory for experiment run
 # Optionally exit from script if directory already exists
 basedir=$scratch/$EXPDIR # helper
-[ ! -z $NEWEXPER ] && $NEWEXPER && [ -d $basedir ] && echo "ERROR: Working directory already exists. Continuing..." && exit 1
+[ ! -z $NEWEXPER ] && $NEWEXPER && [ -d $basedir ] && echo "Error: Working directory already exists. Continuing..." && exit 1
 [ ! -d $basedir ] && mkdir $basedir # make directory
 
-################################################################################
-# Helper functions for model runs
-################################################################################
-# Set up input files for model executable to read; tried to make the function readable
-# by matching indentation, which can be done with <<-DELIM; literal tab chars ignored
-# https://unix.stackexchange.com/questions/76481/cant-indent-heredoc-to-match-nestings-indent
-################################################################################
-# Takes two arguments: 1) the working directory, and 2) the iteration mode
 function Setup() {
   cdir=$1
   ncrecord=$2
   if [ -z $1 ] || [ -z $2 ]; then
-    echo "ERROR: Not enough arguments provided to Setup() function."
+    echo "Error: Not enough arguments provided to Setup() function."
     exit 1
   fi
   if [ -z $radiationoff ] || [ -z $frictionoff ] || [ -z $surfaceoff ]; then
-    echo "ERROR: Required environmental variable not set."
+    echo "Error: Required environmental variable not set."
     exit 1
   fi
   # Set up working directory, and move there
@@ -438,10 +417,10 @@ EOF
 # Take one argument: directory where restart files exist
 function Restart() {
   rdir=$1 # the restart direcotry
-  [ ! -d $rdir ] && echo "ERROR: Restart directory $rdir does not exist." && exit 1
+  [ ! -d $rdir ] && echo "Error: Restart directory $rdir does not exist." && exit 1
   # Copy over relevant restart files for exp type; if missing, raise error
   if [ -z $1 ]; then
-    echo "ERROR: Not enough arguments provided to Restart() function."
+    echo "Error: Not enough arguments provided to Restart() function."
     exit 1
   fi
   if [ "$EXPTYPE" == "spectral" ]; then
@@ -454,7 +433,7 @@ function Restart() {
   echo "Moving restart files from ${rdir##*/}/RESTART to ${PWD##*/}/INPUT..."
   for file in ${resfiles[@]}; do
     if [ ! -r $rdir/RESTART/$file ]; then
-      echo "ERROR: Missing restart file ${rdir##*/}/RESTART/${file}."
+      echo "Error: Missing restart file ${rdir##*/}/RESTART/${file}."
       exit 1
     else
       cp $rdir/RESTART/$file INPUT/$file
@@ -471,7 +450,7 @@ function Iterate() {
   ncrecord=$1
   nckeep=$2
   if [ -z $1 ] || [ -z $2 ]; then
-    echo "ERROR: Not enough arguments provided to Iterate() function."
+    echo "Error: Not enough arguments provided to Iterate() function."
     exit 1
   fi
   start=$(date +%s)
@@ -486,7 +465,7 @@ function Iterate() {
   if [ ! -z $p2 ]; then
     wait $p2; estatus=$? # wait command will always exit with exit status of supplied process ID
     if [ $estatus != 0 ]; then
-      echo "ERROR: Exit status $estatus from previous model step..."
+      echo "Error: Exit status $estatus from previous model step..."
       case $estatus in
         1) echo "Something failed during model integration. Check log.model." ;;
         2) echo "Something failed during model interpolation. Check log.interp." ;;
@@ -529,134 +508,49 @@ function Iterate() {
 # starting points from control for spin-down ensemble experiments
 ##############################################################################
 estatus=0 # initialize exit status
-if $CONTROL; then
-  # CHECK THAT TIMING VARIABLES ARE DECLARED
-  if [ -z $TSTART ] || [ -z $TEND ] || [ -z $TKEEP ] || [ -z $TRECORD ]; then
-    echo "ERROR: One or more of the timing variables was not set."
-    exit 1
-  fi
-  # PREPARE FOR THE LOOP
-  echo "Running control experiment from day $TSTART to day $TEND."
-  origin=$(date +%s) # start time
-  radiationoff=false # we still have radiation now
-  surfaceoff=false
-  frictionoff=false
-  pday=$(($TSTART - $DAYS)) # only time when we do minus days
-  cday=$TSTART
-  nday=$(($TSTART + $DAYS))
-  while [ $nday -le $TEND ]; do
-    # MESSAGE AND RESET TIMER
-    echo "Running from day $cday to day $nday."
-    time=$(date +%s)
-    # RUN THE MODEL and COMBINE OUTPUT
-    # OPTIONALLY USE THE END OF OTHER CONTROL RUNS TO REDUCE SPINUP TIME
-    pdir=$basedir/d$(printf "%04d" $pday)-d$(printf "%04d" $cday)
-    cdir=$basedir/d$(printf "%04d" $cday)-d$(printf "%04d" $nday)
-    if [ ! -z "$PDIR" ]; then
-      pdir=($scratch/$PDIR/d*-d*) # list of possible days
-      pdir="${pdir[-1]}" # pick last one; should be sorted
-      echo "OVERRIDE: Using $pdir for restart files."
-      PDIR= # unset pdir; only ever use this feature on first 'day' of a new experiment
-    fi
-    [[ " ${TRECORD[@]} " =~ " $(printf "%04d" $cday) " ]] && ncrecord=true || ncrecord=false
-    [[ " ${TKEEP[@]} " =~ " $(printf "%04d" $cday) " ]] && nckeep=true || nckeep=false
-    Setup $cdir $ncrecord # sets up working directory, cd into it
-    if [ $? == 0 ]; then # setup fails if user doesn't want to overwrite old experiments; see NEWDAYS option
-      [[ $cday -gt 0 || ! -z $PDIR ]] && Restart $pdir # add restart files
-      $nckeep && echo "Keeping original longitude info."
-      Iterate $ncrecord $nckeep # run model
-    fi
-    # STEP THINGS FORWARD, FOR NEXT ITERATION
-    pday=$cday
-    cday=$(($pday + $DAYS))
-    nday=$(($cday + $DAYS))
-  done
-  echo "Processing last file..."
-  wait $p2
-  p2=
-  echo "The control run completed successfully in $(($(date +%s) - $origin)) seconds!"
-  echo "Timestamp: $(date)."
+# CHECK THAT TIMING VARIABLES ARE DECLARED
+if [ -z $TSTART ] || [ -z $TEND ] || [ -z $TKEEP ] || [ -z $TRECORD ]; then
+  echo "Error: One or more of the timing variables was not set."
+  exit 1
 fi
-
-##############################################################################
-# SPINDOWN RUNS
-# User must specify which namelist params are getting abruptly changed.
-##############################################################################
-if $SPINDOWN; then
-  # CHECK THAT TIMING VARIABLES ARE DECLARED
-  if [ -z $TCONTROL ] || [ -z $TSPINSTART ] || [ -z $TSPINEND ] || [ -z $TSPINRECORD ] || [ -z $TSPINKEEP ]; then
-    # echo TCONTROL $TCONTROL TSPINSTART $TSPINSTART TSPINEND $TSPINEND TSPINRECORD $TSPINRECORD TSPINKEEP $TSPINKEEP
-    echo "ERROR: One or more of the timing variables was not set."
-    exit 1
+# PREPARE FOR THE LOOP
+echo "Running control experiment from day $TSTART to day $TEND."
+origin=$(date +%s) # start time
+radiationoff=false # we still have radiation now
+surfaceoff=false
+frictionoff=false
+pday=$(($TSTART - $DAYS)) # only time when we do minus days
+cday=$TSTART
+nday=$(($TSTART + $DAYS))
+while [ $nday -le $TEND ]; do
+  # MESSAGE AND RESET TIMER
+  echo "Running from day $cday to day $nday."
+  time=$(date +%s)
+  # RUN THE MODEL and COMBINE OUTPUT
+  # OPTIONALLY USE THE END OF OTHER CONTROL RUNS TO REDUCE SPINUP TIME
+  pdir=$basedir/d$(printf "%04d" $pday)-d$(printf "%04d" $cday)
+  cdir=$basedir/d$(printf "%04d" $cday)-d$(printf "%04d" $nday)
+  if [ ! -z "$PDIR" ]; then
+    pdir=($scratch/$PDIR/d*-d*) # list of possible days
+    pdir="${pdir[-1]}" # pick last one; should be sorted
+    echo "OVERRIDE: Using $pdir for restart files."
+    PDIR= # unset pdir; only ever use this feature on first 'day' of a new experiment
   fi
-  # PREPARE FOR THE LOOP
-  case $SPINDOWNOPT in # determine experiment type
-    1) radiationoff=true surfaceoff=true frictionoff=false ;;
-    2) radiationoff=true surfaceoff=false frictionoff=false ;;
-    3) radiationoff=true surfaceoff=true frictionoff=true ;;
-    4) radiationoff=false surfaceoff=false frictionoff=true ;;
-    *) echo "ERROR: Unknown spindown identifier \"$SPINDOWNOPT\"."; exit 1 ;;
-  esac
-  $radiationoff && radiation=off || radiation=on
-  $surfaceoff && surface=off || surface=on
-  $frictionoff && friction=off || friction=on
-  echo "Running spindown experiment $SPINDOWNOPT from days ${TCONTROL[@]} for $TSPINEND days."\
-       "Radiation $radiation, surface radiation $surface, friction $friction."
-  origin=$(date +%s)
-  nckeep=false
-  ncrecord=false
-  # ITERATE THROUGH STARTING DAYS
-  for eday in "${TCONTROL[@]}"; do
-    cday=0 # current day relative to start of equilibrium
-    nday=$(($cday + $DAYS)) # next day, relative to start
-    prefix=$basedir/d$(printf "%04d" $eday) # for successive spindown runs
-    fstart=$basedir/d$(printf "%04d" $(($eday - $DAYS)))-d$(printf "%04d" $eday) # for restart files from control
-    origin=$(date +%s) # record time
-    echo "Starting radiation-off spindown run from day $eday for $TSPINEND days."
-    while [ $nday -le $TSPINEND ]; do
-      # SKIP THIS TIME (OPTIONALLY)
-      if [ $cday -lt $TSPINSTART ]; then
-        echo "Skipping $cday."
-        pday=$cday # previous day
-        cday=$(($pday + $DAYS))
-        nday=$(($cday + $DAYS))
-        continue
-      fi
-      # GET DIRECTORIES
-      cdir=$prefix-spindown$SPINDOWNOPT-d$(printf "%04d" $cday)-d$(printf "%04d" $nday)
-      [ $cday -eq 0 ] && pdir=$fstart || { # new line for visibility
-        pdir=$prefix-spindown$SPINDOWNOPT-d$(printf "%04d" $pday)-d$(printf "%04d" $cday)
-        }
-      # RUN THE MODEL and COMBINE OUTPUT
-      [[ " ${TSPINRECORD[@]} " =~ " $(printf "%04d" $cday) " ]] && ncrecord=true || ncrecord=false
-      [[ " ${TSPINKEEP[@]} " =~ " $(printf "%04d" $cday) " ]] && nckeep=true || nckeep=false
-      Setup $cdir $ncrecord # sets up working directory, cd into it
-      if [ $? == 0 ]; then # returns 1 if we were requested not to overwrite old directories
-        Restart $pdir # add restart files
-        Iterate $ncrecord $nckeep # run model
-      fi
-      # STEP THINGS FORWARD, FOR NEXT ITERATION
-      pday=$cday # previous day
-      cday=$(($pday + $DAYS))
-      nday=$(($cday + $DAYS))
-    done
-    echo "Spindown from $eday completed successfully in $(($(date +%s) - $origin)) seconds!"
-    echo "Timestamp: $(date)."
-  done
-  echo "Processing last file..."
-  wait $p2
-  p2=
-  echo "The spindown runs completed successfuly in $(($(date +%s) - $origin)) seconds!"
-  echo "Timestamp: $(date)."
-fi
-################################################################################
-# Finally, apply post-processing to the output data
-################################################################################
-# if $postprocess; then
-#   echo "Running post-processing steps..."
-#   tpost=$(date +%s)
-#   if $testing; then flags="-t"; else flags=""; fi
-#   $postprocess $flags $FILENAME $scratch $storage ${KAS[@]}
-#   echo "Post-processing finished in $(($(date +%s) - $tpost))s!"
-#   # . deactivate ncl_stable # de-activate the NCL environment
-# fi
+  [[ " ${TRECORD[@]} " =~ " $(printf "%04d" $cday) " ]] && ncrecord=true || ncrecord=false
+  [[ " ${TKEEP[@]} " =~ " $(printf "%04d" $cday) " ]] && nckeep=true || nckeep=false
+  Setup $cdir $ncrecord # sets up working directory, cd into it
+  if [ $? == 0 ]; then # setup fails if user doesn't want to overwrite old experiments; see NEWDAYS option
+    [[ $cday -gt 0 || ! -z $PDIR ]] && Restart $pdir # add restart files
+    $nckeep && echo "Keeping original longitude info."
+    Iterate $ncrecord $nckeep # run model
+  fi
+  # STEP THINGS FORWARD, FOR NEXT ITERATION
+  pday=$cday
+  cday=$(($pday + $DAYS))
+  nday=$(($cday + $DAYS))
+done
+echo "Processing last file..."
+wait $p2
+p2=
+echo "The control run completed successfully in $(($(date +%s) - $origin)) seconds!"
+echo "Timestamp: $(date)."
