Various updates

diff --git a/drycore_run b/drycore_run
--- a/drycore_run
+++ b/drycore_run
@@ -1,14 +1,10 @@
 #!/bin/bash
 ################################################################################
+# README.md file has instructions on namelist/diagnostic table parameters
 # This script runs the GFDL dry core model in blocks of N days, and concurrently
-# processes data with "process" script while next block is run
+# processes data with "process" script while next block is run.
 # Concurrent processing can hugely reduce the amount of time needed to get derived
 # quantities like heat flux and stuff.
-# README.md file has instructions on namelist/diagnostic table parameters
-# * 8  cores: 100-day Control  run, T42 64lats was 1181 seconds
-# * 12 cores: 100-day Spindown run, T39 60lats was 1022 seconds
-# * 8  cores: 10-day  Control  run, T42 64lats was 140  seconds
-# * 12 cores: 10-day  Spindown run, T39 60lats was 111  seconds
 ################################################################################
 # Initial stuff 
 ################################################################################
@@ -36,26 +32,26 @@ process=$cwd/process # *process the parallel-output nc files directly before mer
 # Read the comments to see explanations for each option
 while [ $# -gt 0 ]; do # echo "Flag: $1"
   case "$1" in
-    -n|--new)        new=true    ;; # do not write to existing experiment folders?
-    -r|--resume)     resume=true ;; # do not overwrite existing dXXXX-dYYYY folders?
-    -c|--cores=*)    cores=${1#*=}     ;;
-    -s|--start=*)    tstart=${1#*=}    ;; # starting day
-    -e|--end=*)      tend=${1#*=}      ;; # ending day
-    -m|--mode=*)     mode=${1#*=}      ;; # 0 is control, 1 is spindown, 2...
-    -p|--process=*)  pflags_global="${1#*=}" ;; # flags for processing script
-    -rs|--restart=*)  rdir_override=${1#*=} ;; # manual override restart directory
-    -ds=*|--days-spindown=*) t_spindown=($(echo ${1#*=} | tr ',' ' ')) ;;
-    -dxyz=*|--days-xyzdata=*)  t_xyzdata=($(echo ${1#*=}  | tr ',' ' ')) ;;
-    -dn=*|--days-nodata=*)   t_nodata=($(echo ${1#*=}   | tr ',' ' ')) ;;
+    -n|--new)         new=true ;;       # use this to *exit* if experiment folder already exists
+    -r|--resume)      resume=true ;;    # use this to *autodetect* last day of existing run, continue from there
+    -ts=*|--tstart=*) tstart=${1#*=} ;; # use this to continue from *particular* day of existing run
+    -te=*|--tend=*)   tend=${1#*=} ;;   # ending day
+    -c=*|--cores=*)   cores=${1#*=} ;;
+    -m=*|--mode=*)    mode=${1#*=} ;;   # 0 is control, 1 is spindown, 2...
+    -p=*|--process=*)  pflags_global="${1#*=}" ;; # flags for processing script
+    -rd=*|--restart=*) rdir_override=${1#*=} ;;   # manual override restart directory
+    -ds=*|--days-spindown=*)  t_spindown=($(echo ${1#*=} | tr ',' ' ')) ;;
+    -dxyz=*|--days-xyzdata=*) t_xyzdata=($(echo ${1#*=}  | tr ',' ' ')) ;;
+    -dn=*|--days-nodata=*)    t_nodata=($(echo ${1#*=}   | tr ',' ' ')) ;;
     -*) echo "Error: Unknown flag \"$1\"." && exit 1 ;;
     *)  [ -n "$expdir" ] && echo "Error: More than one experiment directory specified." && exit 1
       expdir="$1" ;;
   esac; shift
 done
-[ -z $expdir ]               && echo "Error: You must declare the experiment directory."    && exit 1
-[[ -z $tstart || -z $tend ]] && echo "Error: Start and end times must be declared."         && exit 1
-[ ${#t_xyzdata[@]} -gt 0 ]   && echo "Preserving full resolution for days: ${t_xyzdata[@]}."
+[ -z $expdir ]               && echo "Error: You must declare the experiment directory." && exit 1
+[[ -z $tstart || -z $tend ]] && echo "Error: Start and end times must be declared."      && exit 1
 [ ${#t_nodata[@]} -gt 0 ]    && echo "Removing all data for days: ${t_nodata[@]}."
+[ ${#t_xyzdata[@]} -gt 0 ]   && echo "Preserving full resolution for days: ${t_xyzdata[@]}."
 [[ $mode -ne 0 && ${#t_spindown[@]} -gt 0 ]] && echo "Starting spindown for days: ${t_spindown[@]}"
 
 # Optionally exit from script if directory already exists
@@ -65,7 +61,7 @@ if [ ! -d $expdir ]; then
   [ $? -ne 0 ] && echo "Error: Could not create experiment directory \"$expdir\"." && exit 1
 fi
 
-# Array membership
+# Usage is array_in value ${array[@]}, behaves like python 'value in array'
 array_in() {
   [[ " ${@:2} " =~ " ${1} " ]]
   return $?
@@ -87,9 +83,83 @@ nml_replace() { # first argument is param name, second argument is value
   done
 }
 days=$(nml_parse days) # number of days in each block
+# Process exit status
+exit_check() {
+  estatus=$1
+  if [ $estatus != 0 ]; then
+    echo "Error: Exit status $estatus from post-processing previous block..."
+    case $estatus in
+      1) echo "NetCDF files missing. Check log.model." ;;
+      2) echo "Something failed during model interpolation. Check log.interp." ;;
+      3) echo "Something failed while getting basic terms. Check log.basic." ;;
+      4) echo "Something failed while getting Lorenz cycle terms. Check log.lorenz." ;;
+      *) echo "Check log.process; other/miscellaneous failure." ;;
+    esac
+    exit 1
+  fi
+}
 
 ################################################################################
-# Helper functions for model runs
+# Function for running the next model step from a previous step
+# applying post-processing to a previous model step in the background, and organizing
+# all the NetCDF files
+################################################################################
+driver() {
+  # Run model in parallel
+  # Previously we set processor affinities
+  local rdir=$1 # the restart direcotry
+  [ $# -ne 1 ] && echo "Error: driver() function takes exactly 1 argument." && exit 1
+  t1=$(date +%s)
+  echo "Running model..."
+  $run -np $cores ./fms.x &>log.model # need ./fms.x, not fms
+  egrep 'EXIT CODE: [1-9]|FATAL from PE' log.model &>/dev/null && \
+    echo "Error: Bad exit code from model run step." && exit 1
+  tmodel=$(cat log.model | grep "Total runtime*" | xargs | cut -d " " -f 5)
+  echo "Model time: ${tmodel%.*}s." # is just max of the two
+  # taskset -p $(taskset -p $$ | cut -d ':' -f 2) $! # match processor affinities
+  # taskset -cp 0-19 $! 1>/dev/null # $! == pid of last job run in background
+
+  # Check that model ran successfully
+  # FMS prints error messages to standard output but doesn't actually set
+  # the exit code/mpirun doesn't pass that exit code, which is fucking dumb.
+  # We parse the logfile instead
+  # egrep 'EXIT CODE: [1-9]|FATAL from PE' log.model &>/dev/null && \
+  #   echo "Error: Bad exit code from model run step." && exit 1
+  # Wait for previous processing step, if set
+  # If unset, means we are just now starting the model run
+  # if [ -n "$pp" ]; then # post-processing is active
+  #   echo "Wating for process: $pp"
+  #   wait $pp # wait command will always exit with exit status of supplied process ID
+  #   exit_check $?
+  # fi
+  # Echo timing information from previous run
+  # Processing was run in parallel, remember
+  # tmodel=$(cat log.model | grep "Total runtime*" | xargs | cut -d " " -f 5)
+  # echo "Model time: ${tmodel%.*}s." # is just max of the two
+  # if [ -r $rdir/log.process ]; then
+  #   tprocess=$(tail -1 $rdir/log.process | sed 's/[^0-9]*//g' )
+  #   echo "Model time: ${tmodel%.*}s, Previous process time: ${tprocess%.*}s."
+  # else
+  #   echo "Model time: ${tmodel%.*}s." # is just max of the two
+  # fi
+
+  # Remove some files
+  # [ -r INPUT/topography.data.nc ] && rm INPUT/topography.data.nc # remove topography
+  [ -d INPUT ] && rm -r INPUT # remove everything
+  [ -r logfile.0000.out ] && mv logfile.0000.out log.init # contains init info
+  rm fms.x # remove executable, because takes up space
+
+  # Process new data, and remove old data
+  # Previously we set processor affinities, but didn't help much
+  echo "Calling processing script with flags: $(echo $pflags_day $pflags_global | xargs)"
+  $process $pflags_day $pflags_global &>log.process
+  exit_check $?
+  tprocess=$(tail -1 $rdir/log.process | sed 's/[^0-9]*//g' )
+  echo "Process time: ${tprocess%.*}s."
+  # taskset -p $(taskset -p $$ | cut -d ':' -f 2) $!
+  # taskset -cp 20-23 $! 1>/dev/null # send to particular CPUs
+}
+
 ################################################################################
 # Set up input files for model executable to read
 # Takes two arguments: 1) the working directory, and 2) the iteration mode
@@ -154,73 +224,6 @@ dir_setup() {
 }
 
 ################################################################################
-# Function for running the next model step from a previous step
-# applying post-processing to a previous model step in the background, and organizing
-# all the NetCDF files
-################################################################################
-driver() {
-  # Run model in parallel
-  # Previously we set processor affinities
-  local rdir=$1 # the restart direcotry
-  [ $# -ne 1 ] && echo "Error: driver() function takes exactly 1 argument." && exit 1
-  t0=$(date +%s)
-  echo "Running model..."
-  $run -np $cores ./fms.x &>log.model # need ./fms.x, not fms
-  # taskset -p $(taskset -p $$ | cut -d ':' -f 2) $! # match processor affinities
-  # taskset -cp 0-19 $! 1>/dev/null # $! == pid of last job run in background
-
-  # Check that model ran successfully
-  # FMS prints error messages to standard output but doesn't actually set
-  # the exit code/mpirun doesn't pass that exit code, which is fucking dumb.
-  # We parse the logfile instead
-  egrep 'EXIT CODE: [1-9]|FATAL from PE' log.model &>/dev/null && \
-    echo "Error: Bad exit code from model run step." && exit 1
-
-  # Wait for previous processing step, if set
-  # If unset, means we are just now starting the model run
-  if [ ! -z $pp ]; then # post-processing is active
-    wait $pp; estatus=$? # wait command will always exit with exit status of supplied process ID
-    if [ $estatus != 0 ]; then
-      echo "Error: Exit status $estatus from post-processing previous block..."
-      case $estatus in
-        1) echo "NetCDF files missing. Check log.model." ;;
-        2) echo "Something failed during model interpolation. Check log.interp." ;;
-        3) echo "Something failed while getting basic terms. Check log.basic." ;;
-        4) echo "Something failed while getting Lorenz cycle terms. Check log.lorenz." ;;
-        *) echo "Check log.process; other/miscellaneous failure." ;;
-      esac
-      exit 1
-    fi
-  fi
-
-  # Echo timing information from previous run
-  # Processing was run in parallel, remember
-  if [ -r $rdir/log.process ]; then
-    tmodel=$(cat log.model | grep "Total runtime*" | xargs | cut -d " " -f 5)
-    tprocess=$(tail -1 $rdir/log.process | sed 's/[^0-9]*//g' )
-    echo "Model time: ${tmodel%.*}s, Process time: ${tprocess%.*}s."
-    if [ "$tprocess" -eq "${tmodel%%.*}" ] 2>/dev/null; then
-      echo "Model completion time MINUS processing time: $((${tmodel%%.*} - $tprocess))s."
-    fi
-  fi
-  echo "Time for integration: $(($(date +%s) - $t0))s."
-
-  # Remove some files
-  # [ -r INPUT/topography.data.nc ] && rm INPUT/topography.data.nc # remove topography
-  [ -d INPUT ] && rm -r INPUT # remove everything
-  [ -r logfile.0000.out ] && mv logfile.0000.out log.init # contains init info
-  rm fms.x # remove executable, because takes up space
-
-  # Process new data, and remove old data
-  # Previously we set processor affinities, but didn't help much
-  echo "Calling processing script with flags: $(echo $pflags_day $pflags_global | xargs)"
-  $process $pflags_day $pflags_global &>log.process &
-  pp=$! # record PID
-  # taskset -p $(taskset -p $$ | cut -d ':' -f 2) $!
-  # taskset -cp 20-23 $! 1>/dev/null # send to particular CPUs
-}
-
-################################################################################
 # Function for restarting model; put correct files in correct place so 
 # fms can read them and continue iteration from a previous state.
 ################################################################################
@@ -253,12 +256,19 @@ case $mode in
   # PREPARE FOR THE LOOP
   echo "Running control experiment from day $tstart to day $tend on $cores cores, restart every $days days."
   coldstart=true # assume cold start by default
-  origin=$(date +%s) # start time
-  pday=$(($tstart - $days)) # only time when we do minus days
-  cday=$tstart
-  nday=$(($tstart + $days))
+  t0=$(date +%s) # start time
+  pday=0 # only time when we do minus days
+  cday=0
+  nday=$days
   while [ $nday -le $tend ]; do
     # MESSAGE AND RESET TIMER/FLAGS
+    # SKIP THIS TIME (OPTIONALLY)
+    if [ $cday -lt $tstart ]; then
+      pday=$cday # previous day
+      cday=$((pday + days))
+      nday=$((cday + days))
+      continue
+    fi
     echo "Running from day $cday to day $nday."
     time=$(date +%s)
     # RUN THE MODEL and COMBINE OUTPUT
@@ -276,8 +286,8 @@ case $mode in
       [ ! -d $rdir ] && echo "Error: Override restart directory \"$rdir\" does not exist." && exit 1
     fi
     unset pflags_day
-    array_in $cday ${t_nodata[@]} && pflags_day+=" -q"
-    array_in $cday ${t_xyznodata[@]} && pflags_day+=" -k"
+    array_in $cday ${t_nodata[@]} && pflags_day+=" -q" && echo "Will delete output netcdf files."
+    array_in $cday ${t_xyzdata[@]} && pflags_day+=" -k" && echo "Will keep XYZ netcdf files."
     dir_setup $cdir # sets up working directory, cd into it
     if [ $? -eq 0 ]; then # setup returns 1 if directory is present and 'resume' option is set
       if ! $coldstart || [ $cday -gt 0 ]; then
@@ -291,14 +301,18 @@ case $mode in
     [ $days -eq 0 ] && break
     # STEP THINGS FORWARD, FOR NEXT ITERATION
     pday=$cday
-    cday=$(($pday + $days))
-    nday=$(($cday + $days))
+    cday=$((pday + days))
+    nday=$((cday + days))
   done
+  # LAST FILE
   echo "Processing last file..."
-  wait $pp; pp=
+  wait $pp
+  exit_check $?
+  unset pp
   tprocess=$(tail -1 log.process | sed 's/[^0-9]*//g')
   echo "Final process time: ${tprocess%.*}s."
-  echo "The control run completed successfully in $(($(date +%s) - $origin)) seconds!"
+  # MESSAGE
+  echo "The control run completed successfully in $(($(date +%s) - t0)) seconds!"
   echo "Timestamp: $(date)."
 
 ##############################################################################
@@ -309,22 +323,22 @@ case $mode in
   [ -z $t_spindown ] && echo "Error: Must declare starting times for spindown experiments." && exit 1
   # PREPARE FOR THE LOOP
   echo "Running spindown experiment $mode from days ${t_spindown[@]} for $tend days, restart every $days days."
-  origin=$(date +%s)
+  t0=$(date +%s)
   # ITERATE THROUGH STARTING DAYS
   for eday in "${t_spindown[@]}"; do
     cday=0 # current day relative to start of equilibrium
-    nday=$(($cday + $days)) # next day, relative to start
+    nday=$days # next day, relative to start
     prefix=$expdir/d$(printf "%04d" $eday) # for successive spindown runs
-    fstart=$expdir/d$(printf "%04d" $(($eday - $days)))-d$(printf "%04d" $eday) # for restart files from control
-    origin=$(date +%s) # record time
+    fstart=$expdir/d$(printf "%04d" $((eday - days)))-d$(printf "%04d" $eday) # for restart files from control
+    ts=$(date +%s) # record time
     echo "Starting radiation-off spindown run from day $eday for $tend days."
     while [ $nday -le $tend ]; do
       # SKIP THIS TIME (OPTIONALLY)
       if [ $cday -lt $tstart ]; then
-        echo "Skipping $cday."
+        echo "Skipping day $cday."
         pday=$cday # previous day
-        cday=$(($pday + $days))
-        nday=$(($cday + $days))
+        cday=$((pday + days))
+        nday=$((cday + days))
         continue
       fi
       # GET DIRECTORIES
@@ -342,17 +356,18 @@ case $mode in
       fi
       # STEP THINGS FORWARD, FOR NEXT ITERATION
       pday=$cday # previous day
-      cday=$(($pday + $days))
-      nday=$(($cday + $days))
+      cday=$((pday + days))
+      nday=$((cday + days))
     done
-    echo "Spindown from $eday completed successfully in $(($(date +%s) - $origin)) seconds!"
+    echo "Spindown from $eday completed successfully in $(($(date +%s) - ts)) seconds!"
     echo "Timestamp: $(date)."
   done
   echo "Processing last file..."
   tprocess=$(tail -1 log.process | sed 's/[^0-9]*//g')
   wait $pp; pp=
-  echo "The spindown runs completed successfuly in $(($(date +%s) - $origin)) seconds!"
+  echo "The spindown runs completed successfuly in $(($(date +%s) - t0)) seconds!"
   echo "Timestamp: $(date)."
+
 ################################################################################
 # Other experiments types can go below
 ################################################################################
diff --git a/process b/process
--- a/process
+++ b/process
@@ -30,14 +30,17 @@ _debug=false   # keep data in original folder, instead of moving to ../netcdf? u
 _resume=false  # process old "full" files?
 _keepxyz=false # keep original "full" results?
 _combine=false # only combine model files, nothing else?
+_splitxyz=true # make true the default
+nsplit=4 # number of time splits for XYZ files
 while [ $# -gt 0 ]; do
   case $1 in
     -c|--combine) echo "Only combining files." && _combine=true ;;
     -q|--quit) echo "Skipping processing." && exit 0 ;;
-    -d=*|--dir=*)  _dir=${1##*=} ;;
+    -d=*|--dir=*) _dir=${1##*=} ;;
     -d|--debug)  _debug=true   ;;  # if true, keep all intermediate files
     -r|--resume) _resume=true  ;; # process old results sitting in the directory
     -k|--keep)   _keepxyz=true ;; # whether to keep longitudinal data
+    -s|--split) _splitxyz=true ;; # whether to split XYZ files before combining
     *) echo "Error: Unknown flag \"$1\"." && exit 127 ;;
   esac
   shift # shift by one
@@ -57,12 +60,12 @@ means=$bin/process_means.ncl     # just gets zonal means
 cd $_dir # optionally pass dir argument
 
 # Double check some stuff
-[ ! -r $process ]        && echo "Error: The script \"$process\" is missing."                       && exit 127
-[ ! -r $interp_ncl ]     && echo "Error: The script \"$interp_ncl\" is missing."                    && exit 127
-[ ! -x $mppnccombine ]  && echo "Error: The mpp combine executable \"$mppnccombine\" is missing." && exit 127
-! hash ncl 2>/dev/null  && echo "Error: NCL is not in $PATH."                                     && exit 127
-! hash cdo 2>/dev/null  && echo "Error: CDO is not in $PATH."                                     && exit 127
-! hash ncks 2>/dev/null && echo "Error: NCO is not in $PATH."                                     && exit 127
+[ ! -r $process ]       && echo "Error: The script \"$process\" is missing."          && exit 127
+[ ! -r $interp_ncl ]    && echo "Error: The script \"$interp_ncl\" is missing."       && exit 127
+[ ! -x $mppnccombine ]  && echo "Error: The executable \"$mppnccombine\" is missing." && exit 127
+! hash ncl 2>/dev/null  && echo "Error: NCL is not in $PATH."                         && exit 127
+! hash ncks 2>/dev/null && echo "Error: NCO is not in $PATH."                         && exit 127
+# ! hash cdo 2>/dev/null  && echo "Error: CDO is not in $PATH."                       && exit 127
 
 ################################################################################
 # Functions
@@ -79,11 +82,12 @@ hybrid_to_press() {
   t=$(date +%s)
 
   # Apply some simple modifications to attributes
-  ncrename -d pfull,mlev $filename &>/dev/null # mlev is the ECHAM convention, needed for CDO interpolation
-  ncrename -d phalf,ilev $filename &>/dev/null # ilev is the other ECHAM convention
-  ncrename -v pfull,mlev $filename &>/dev/null # -d renames dimensions, -v renames variables of same name
-  ncrename -v phalf,ilev $filename &>/dev/null
-  ncatted -O -a bounds,mlev,o,c,"ilev" $filename
+  # NOTE: Use -h to prevent appending history
+  ncrename -h -d pfull,mlev $filename &>/dev/null # mlev is the ECHAM convention, needed for CDO interpolation
+  ncrename -h -d phalf,ilev $filename &>/dev/null # ilev is the other ECHAM convention
+  ncrename -h -v pfull,mlev $filename &>/dev/null # -d renames dimensions, -v renames variables of same name
+  ncrename -h -v phalf,ilev $filename &>/dev/null
+  ncatted -h -O -a bounds,mlev,o,c,"ilev" $filename
 
   # Interpolation
   echo "Interpolating with NCL..." # -Q = no banner, -n = do not enumerate print statements
@@ -98,13 +102,16 @@ hybrid_to_press() {
   # a few special ones like 'axis' and 'standard_name'
   # NOTE: This is really fast (0.02s on T42 20 day file)
   # This is much faster than even editing one attribute in NCL (0.05s)
-  ncatted -O -a NumFilesInSet,global,o,l,$numfiles \
+  # NOTE: We set the calendar to '360_day' because that seems reasonable for
+  # an equinoctial model run (even months of 30), and software like CDO and
+  # xarray cannot interpret the default 'NO_CALENDAR'
+  ncatted -h -O -a NumFilesInSet,global,o,l,$numfiles \
     -a edges,lon,d,, -a edges,lat,d,, \
     -a axis,lon,o,c,"X" -a axis,lat,o,c,"Y" -a axis,plev,o,c,"Z" -a axis,time,o,c,"T" \
     -a long_name,plev,o,c,"pressure_level" -a units,plev,o,c,"mb" -a bounds,plev,o,c,"plev_bnds" \
     -a long_name,lat,o,c,"latitude"  -a standard_name,lat,o,c,"latitude" \
     -a long_name,lon,o,c,"longitude" -a standard_name,lon,o,c,"longitude" \
-    -a standard_name,time,o,c,"time" \
+    -a calendar_type,time,d,, -a calendar,time,o,c,"360_day" -a standard_name,time,o,c,"time" \
     -a units,lat,o,c,"degrees_north" -a units,lon,o,c,"degrees_east" $output
   ! $_debug && mv $output $filename # move old file on top of new file
   echo "  * Time for interpolation: $(($(date +%s) - t))s."
@@ -174,25 +181,25 @@ for file in ${files[@]}; do
   # File names and such
   base=${file%%.*}
   if $_debug && $_resume; then
-    parts=(${base}.*.nc) # check if already present
+    ncfiles=(${base}.*.nc) # check if already present
   elif $_resume; then
-    parts=(${file})
+    ncfiles=(${file})
   else
     for part in ${base}.nc*; do
       num=${part##*.}
       mv $part ${base}.${num}.nc & # some programs won't recognize file without .nc extension
     done
     wait # in background
-    parts=(${base}.*.nc)
+    ncfiles=(${base}.*.nc)
   fi
-  echo Files: ${parts[@]}
-  numfiles=${#parts[@]}
+  echo Files: ${ncfiles[@]}
+  numfiles=${#ncfiles[@]}
   xyzfile="${base}_full.${PWD##*/}.nc"   # original data
   yzfile="${base}_summary.${PWD##*/}.nc" # longitude-averaged data
   # Just want to combine files and exit?
   if $_combine; then
     [ -r ${base}.nc ] && rm ${base}.nc
-    $mppnccombine -r ${base}.nc  ${parts[@]}
+    $mppnccombine -r ${base}.nc ${ncfiles[@]}
     continue
   fi
 
@@ -202,7 +209,7 @@ for file in ${files[@]}; do
   tp=$(date +%s)
   echo "Interpolating and getting means..."
   ! [ -d LOGS ] && mkdir LOGS
-  for ncfile in ${parts[@]}; do
+  for ncfile in ${ncfiles[@]}; do
     if ! $_debug && $_resume; then
       # Just get means
       num=0000
@@ -217,20 +224,9 @@ for file in ${files[@]}; do
       $_debug && mfile=${ncfile%%.*}_interp.$suffix || mfile=$ncfile
       { hybrid_to_press "$ncfile" "$suffix"; means "$mfile" "$suffix"; } &>LOGS/log.$num &
     fi
-  done
-  wait
-  $_debug && parts=(${base}_interp.*.nc) # we didn't overwrite them
+  done; wait
+  $_debug && ncfiles=(${base}_interp.*.nc) # we didn't overwrite them
   echo "  * Time for interpolating and getting zonal means in parallel: $(($(date +%s) - tp))s."
-  # Merge the files
-  # NOTE: Use mppnccombine -h to print help info; the -r removes files after
-  # run was successful
-  if $_parallel; then
-    echo "Combining zonal mean files..."
-    t=$(date +%s)
-    [ -r means.nc ] && rm means.nc
-    $mppnccombine means.nc means.*.nc
-    echo "  * Time for combining zonal mean files: $(($(date +%s) - t))s."
-  fi
 
   ##############################################################################
   # 2) Calculate other params in parallel
@@ -238,7 +234,7 @@ for file in ${files[@]}; do
   # Global means were required for some, hence the initial merge
   tp=$(date +%s)
   echo "Getting other params..."
-  for ncfile in ${parts[@]}; do
+  for ncfile in ${ncfiles[@]}; do
     # Number
     if $_resume && ! $_debug; then
       num=0000
@@ -249,48 +245,111 @@ for file in ${files[@]}; do
       suffix=${num}.nc
     fi
     params "$ncfile" "$suffix" &>>LOGS/log.${num} &
-  done
-  wait
+  done; wait
   echo "  * Time for getting params in parallel: $(($(date +%s) - tp))s."
-  # Merge the files
+
+  # Merge zonal means
+  # NOTE: Use mppnccombine -h to print help info; the -r removes files after
+  # run was successful
   if $_parallel; then
-    echo "Combining param files..."
+    # Merge params
+    echo "Combining YZ files..."
     t=$(date +%s)
+    [ -r means.nc ] && rm means.nc
     [ -r params.nc ] && rm params.nc
-    $mppnccombine params.nc params.*.nc
-    echo "  * Time for combining param files: $(($(date +%s) - t))s."
+    ! $_debug && cflag='-r'
+    $mppnccombine $cflag means.nc means.*.nc &
+    $mppnccombine $cflag params.nc params.*.nc &
+    wait
+    echo "  * Time for combining files: $(($(date +%s) - t))s."
   fi
-  # Append means to file
-  ncks -A means.nc params.nc
-  $_debug && _cmd=cp || _cmd=mv
-  $_cmd params.nc $yzfile
-  # Cleanup
-  ! $_debug && rm means.nc means.*.nc params.*.nc
+  # Append params to file; want them to show up at end of ncdump ideally
+  # ncks -h --no-abc -A means.nc params.nc
+  ncks -h --no-abc -A params.nc means.nc
+  if $_debug; then
+    cp means.nc $yzfile
+  else
+    mv means.nc $yzfile
+    rm params.nc
+  fi
 
   ##############################################################################
   # 3) Optionally merge the pressure-interpolated files
-  ##############################################################################
   # TODO: Consider reducing to a standard horizontal resolution at least, if
   # not vertical? This could save considerable space.
+  # NOTE: Had error on Cheyenne where mppnccombine failed for sufficiently
+  # big files (threshold was somewhere between 60-80 timesteps at T106 resolution)
+  # To fix this, we take time hyperslabs, merge each half, then re-combine
+  ##############################################################################
+  # Delete the old file
   if ! $_keepxyz; then
-    # Delete the old file
     echo "Removing XYZ files..."
-    ! $_debug && rm ${parts[@]} # simple
-  elif ! $_resume || $_debug; then
-    # Merge files
-    # Will drop variables in parallel before merging
+    ! $_debug && rm ${ncfiles[@]} # simple
+  # Merge files
+  # Will drop variables in parallel before merging
+  elif ! $_resume; then
     t=$(date +%s)
+    unset interp # empty array
     echo "Keeping XYZ files..."
-    for ncfile in ${parts[@]}; do
-      # ncks -O -d time,1,,2 -x -v omega,udt,vdt,tdt $ncfile $ncfile &
-      $_debug && out=${ncfile%%.*}_x.${ncfile#*.} || out=$ncfile
-      ncks -O -x -v omega,udt,vdt,tdt $ncfile $out &
-      interp+=($out)
-    done
-    wait
-    [ -r $xyzfile ] && rm $xyzfile
-    $mppnccombine -r $xyzfile ${interp[@]}
-    echo "  * Time for combining XYZ files: $(($(date +%s) - t))s."
+    keep=plev_bnds,latb,lonb,slp,u,v,t
+    # Without splitting in half
+    if ! $_splitxyz; then
+      for ncfile in ${ncfiles[@]}; do
+        $_debug && out=${ncfile%%.*}_x.${ncfile#*.} || out=$ncfile
+        ncks -O -h --no-abc -v plev_bnds,slp,u,v,t $ncfile $out &
+        interp+=($out)
+      done; wait
+      echo "  * Time for trimming variables: $(($(date +%s) - t))s."
+      t=$(date +%s)
+      echo "Combine full files."
+      [ -r $xyzfile ] && rm $xyzfile
+      $mppnccombine -r $xyzfile ${interp[@]}
+      [ $? -ne 0 ] && echo "Error: Failed to combine XYZ files." && exit 127
+      echo "  * Time for combining XYZ files: $(($(date +%s) - t))s."
+    # Split into files of *n* timesteps
+    else
+      # First a simple test
+      ts=$(ncdump -h ${ncfiles[0]} | grep 'UNLIMITED' | sed 's/[^0-9]//g')
+      [ -z "$ts" ] && echo "Error: Unknown timesteps for file ${ncfiles[0]}." && exit 127
+      [ $((ts % nsplit)) -eq 1 ] && echo "Error: Incompatible number of timesteps ${ts} for ${nsplit} splits." && exit 127
+      # Bugfix; had issues with lost memory even on 109GB nodes, maybe has
+      # to do with hardware architecture or something
+      for ni in $(seq 1 $nsplit); do
+        unset outs
+        for ncfile in ${ncfiles[@]}; do
+          out=${ncfile%%.*}_x${ni}.${ncfile#*.}
+          t1=$(((ni - 1)*ts/nsplit)) # e.g. nsplit=10, ts=200, goes 0, 20, 40, 60
+          t2=$((ni*ts/nsplit - 1)) # e.g. nsplit=10, ts=200, goes 19, 39, 59
+          ncks -O -h --no-abc -d time,$t1,$t2 -v $keep $ncfile $out &
+          outs+=" $out"
+        done
+        interp+=("$outs")
+      done; wait
+      echo "  * Time for trimming variables: $(($(date +%s) - t))s."
+      t=$(date +%s)
+      # Combine groups of half-files
+      i=1
+      unset ps xyzfiles
+      echo "Combine pieces..."
+      for group in "${interp[@]}"; do
+        ixyzfile=${xyzfile%.nc}_${i}.nc
+        $mppnccombine -r $ixyzfile $group &
+        xyzfiles+=($ixyzfile)
+        ps+=($!)
+        let i+=1
+      done
+      for p in ${ps[@]}; do
+        wait $p
+        [ $? -ne 0 ] && echo "Error: Failed to combine XYZ files." && exit 127
+      done
+      echo "  * Time for combining XYZ files: $(($(date +%s) - t))s."
+      # Put back together
+      t=$(date +%s)
+      echo "Put back together..."
+      ncrcat -O ${xyzfiles[@]} $xyzfile
+      ! $_debug && rm ${xyzfiles[@]} ${ncfiles[@]}
+      echo "  * Time for putting XYZ files back together: $(($(date +%s) - t))s."
+    fi
   fi
 
   ##############################################################################
