Added absolute vorticity to longitude-latitude files. No longer saving potential temperature and stability. Spline interpolation instead of linear. No longer syncing compiled source.

diff --git a/drycore_run b/drycore_run
--- a/drycore_run
+++ b/drycore_run
@@ -82,6 +82,7 @@ if [ ! -x $postprocess ]; then
   exit 1
 fi
 # Base directory for experiment run
+# Optionally exit from script if directory already exists
 basedir=$scratch/$EXPDIR # helper
 [ ! -z $NEWEXPER ] && $NEWEXPER && [ -d $basedir ] && echo "ERROR: Working directory already exists. Continuing..." && exit 1
 [ ! -d $basedir ] && mkdir $basedir # make directory
@@ -398,17 +399,17 @@ EOF
 # Variables to save (module name, fortran name, save name, file name, time-sampling freq 
 # for averages, whether we take average, other options, and save size [currently F32]; 
 # note cannot save time-average data in same file as non-time-average data, it seems)
-"dynamics",   "temp",           "t",     "$FILENAME", "all", .false., "none", 2,
-"dynamics",   "ucomp",          "u",     "$FILENAME", "all", .false., "none", 2,
-"dynamics",   "vcomp",          "v",     "$FILENAME", "all", .false., "none", 2,
-"dynamics",   "height",         "z",     "$FILENAME", "all", .false., "none", 2,
-"dynamics",   "slp",            "slp",   "$FILENAME", "all", .false., "none", 2,
-"dynamics",   "omega",          "omega", "$FILENAME", "all", .false., "none", 2,
-"dynamics",   "bk",             "hybi",  "$FILENAME", "all", .false., "none", 2,
-"dynamics",   "pk",             "hyai",  "$FILENAME", "all", .false., "none", 2,
-"hs_forcing", "tdt_ndamp",      "ndamp", "$FILENAME", "all", .false., "none", 2,
-"hs_forcing", "udt_rdamp",      "udamp", "$FILENAME", "all", .false., "none", 2,
-"hs_forcing", "vdt_rdamp",      "vdamp", "$FILENAME", "all", .false., "none", 2,
+"dynamics",   "temp",      "t",     "$FILENAME", "all", .false., "none", 2,
+"dynamics",   "ucomp",     "u",     "$FILENAME", "all", .false., "none", 2,
+"dynamics",   "vcomp",     "v",     "$FILENAME", "all", .false., "none", 2,
+"dynamics",   "height",    "z",     "$FILENAME", "all", .false., "none", 2,
+"dynamics",   "slp",       "slp",   "$FILENAME", "all", .false., "none", 2,
+"dynamics",   "omega",     "omega", "$FILENAME", "all", .false., "none", 2,
+"dynamics",   "bk",        "hybi",  "$FILENAME", "all", .false., "none", 2,
+"dynamics",   "pk",        "hyai",  "$FILENAME", "all", .false., "none", 2,
+"hs_forcing", "tdt_ndamp", "ndamp", "$FILENAME", "all", .false., "none", 2,
+"hs_forcing", "udt_rdamp", "udamp", "$FILENAME", "all", .false., "none", 2,
+"hs_forcing", "vdt_rdamp", "vdamp", "$FILENAME", "all", .false., "none", 2,
 EOF
   else echo "Recording no data."
   fi
@@ -437,6 +438,7 @@ EOF
 # Take one argument: directory where restart files exist
 function Restart() {
   rdir=$1 # the restart direcotry
+  [ ! -d $rdir ] && echo "ERROR: Restart directory $rdir does not exist." && exit 1
   # Copy over relevant restart files for exp type; if missing, raise error
   if [ -z $1 ]; then
     echo "ERROR: Not enough arguments provided to Restart() function."
@@ -452,7 +454,7 @@ function Restart() {
   echo "Moving restart files from ${rdir##*/}/RESTART to ${PWD##*/}/INPUT..."
   for file in ${resfiles[@]}; do
     if [ ! -r $rdir/RESTART/$file ]; then
-      echo "ERROR: Missing restart file ${rdir##*/}/RESTART/$file"
+      echo "ERROR: Missing restart file ${rdir##*/}/RESTART/${file}."
       exit 1
     else
       cp $rdir/RESTART/$file INPUT/$file
@@ -547,16 +549,20 @@ if $CONTROL; then
     echo "Running from day $cday to day $nday."
     time=$(date +%s)
     # RUN THE MODEL and COMBINE OUTPUT
+    # OPTIONALLY USE THE END OF OTHER CONTROL RUNS TO REDUCE SPINUP TIME
     pdir=$basedir/d$(printf "%04d" $pday)-d$(printf "%04d" $cday)
     cdir=$basedir/d$(printf "%04d" $cday)-d$(printf "%04d" $nday)
-    [ ! -z $PDIR ] && pdir=$basedir/$PDIR && echo "OVERRIDE: Using $pdir for restart files."
-    # this way we can start an integration after spinup, say day 1000, and just
-    # integrate for say 1 day; useful for testing different output options
+    if [ ! -z "$PDIR" ]; then
+      pdir=($scratch/$PDIR/d*-d*) # list of possible days
+      pdir="${pdir[-1]}" # pick last one; should be sorted
+      echo "OVERRIDE: Using $pdir for restart files."
+      PDIR= # unset pdir; only ever use this feature on first 'day' of a new experiment
+    fi
     [[ " ${TRECORD[@]} " =~ " $(printf "%04d" $cday) " ]] && ncrecord=true || ncrecord=false
     [[ " ${TKEEP[@]} " =~ " $(printf "%04d" $cday) " ]] && nckeep=true || nckeep=false
     Setup $cdir $ncrecord # sets up working directory, cd into it
-    if [ $? == 0 ]; then
-      [ $cday -gt 0 ] && Restart $pdir # add restart files
+    if [ $? == 0 ]; then # setup fails if user doesn't want to overwrite old experiments; see NEWDAYS option
+      [[ $cday -gt 0 || ! -z $PDIR ]] && Restart $pdir # add restart files
       $nckeep && echo "Keeping original longitude info."
       Iterate $ncrecord $nckeep # run model
     fi
diff --git a/postprocess_funcs b/postprocess_funcs
--- a/postprocess_funcs
+++ b/postprocess_funcs
@@ -7,6 +7,7 @@ shopt -s nullglob # will return empty if no match
 [ -z $SPINDOWNSTART ] && SPINDOWNSTART=9999
 [ -z $SPINDOWNEND ] && SPINDOWNEND=0
 # File management/names
+cwd=$(pwd) # current directory
 log=log_ # log prefix
 fprefix=${FILENAME}_summary # original prefix file names
 fclimate=${FILENAME}_climate.nc
@@ -80,18 +81,23 @@ done
 # and with other datasets; note remap will output an array of NaNs if you try
 # to use remapycon or area weighted maps; with one-longitude, area weighted map
 # is the same as a 'distance weighted' map, so use that one
+interpncl=$cwd/postprocess_interp.ncl # interpolation script
 griddes=eraint_griddes.txt
 zaxisdes=eraint_zaxisdes.txt
 [ ! -r $griddes ] && echo "ERROR: Could not find grid description file $cwd/$griddes." && exit 1
+lat_out=$(cat $griddes | grep -A100 "yvals" | sed 's/[^0-9. -]//g' | xargs | tr ' ' ',')
 [ ! -r $zaxisdes ] && echo "ERROR: Could not find zaxis description file $cwd/$zaxisdes." && exit 1
-eralevels=$(cat eraint_zaxisdes.txt | grep -A100 "levels" | grep -B100 "lbounds" | \
+plev_out=$(cat eraint_zaxisdes.txt | grep -A100 "levels" | grep -B100 "lbounds" | \
   sed '$d' | sed 's/[^0-9]*//' | xargs | tr ' ' ',') # the ERA-Interim level list
-[ -z $eralevels ] && echo "ERROR: Could not parse interpolation levels from $cwd/$zaxisdes." && exit 1
+[ -z $lat_out ] && echo "ERROR: Could not parse interpolation latitudes from $cwd/$griddes." && exit 1
+[ -z $plev_out ] && echo "ERROR: Could not parse interpolation levels from $cwd/$zaxisdes." && exit 1
+# vinterp="-genlevelbounds,ztop=1013.25,zbot=0 -setzaxis,$cwd/$zaxisdes -intlevel,$plev_out" # don't need genlevelbounds because setzaxis adds bounds
 # export CDO_GRIDSEARCH_RADIUS=5 # search radius; consider changing this
-# vinterp="-genlevelbounds,ztop=1013.25,zbot=0 -setzaxis,$cwd/$zaxisdes -intlevel,$eralevels" # don't need genlevelbounds because setzaxis adds bounds
 export REMAP_EXTRAPOLATE="on" # turn extrapolation on
-hinterp="-remapdis,$cwd/$griddes,2"
-vinterp="-setzaxis,$cwd/$zaxisdes -intlevel,$eralevels"
+# Attempts to interpolate with CDO that failed
+# hinterp="-remapdis,$cwd/$griddes,2" # fails for some reason
+hinterp="-remapbic,$cwd/$griddes" # try remapbil
+vinterp="-setzaxis,$cwd/$zaxisdes -intlevel,$plev_out"
 interp="$vinterp $hinterp"
  # 2 says to consider only 2 nearest neighbors; otherwise get artifacts because default
  # behavior is probably 4-8 cells; algorithm doesn't know we have a 2D 'slice'
@@ -110,13 +116,30 @@ function Climate() {
     echo "ERROR: No climate files available between days ${CLIMOSTART} and ${CLIMOEND}."
     exit 1
   fi
-  # Very simple function
+  # Combine time-means of individual files saved during control run
+  rm tmp?.nc &>/dev/null # remove existing tmp files
   echo "Getting temporal mean from days ${climofiles[@]##*/${fprefix}.}."
-  commands=("${climofiles[@]/#/ -timmean }")
-  cdo $flags -ensmean ${commands[@]} tmp.nc
-  echo "Interpolating result."
-  cdo $flags $interp tmp.nc $fclimate; rm tmp.nc
-  [ ! -e $fclimate ] && echo "ERROR: $fclimate not produced." && exit 1
+  commands=("${climofiles[@]/#/ -timmean -delname,s,pt }") # delete static
+    # stability metric and potential temperature if they are present; if not,
+    # this function will just raise a warning
+  cdo $flags -ensmean ${commands[@]} tmp1.nc
+  # CDO interpolation
+  # echo "Interpolating with CDO."
+  # cdo $flags $interp tmp1.nc $fclimate; rm tmp?.nc
+  # [ ! -e $fclimate ] && echo "ERROR: $fclimate not produced." && exit 1
+  # NCL interpolation
+  echo "Interpolating with NCL."
+  ncl -n -Q "filename=\"tmp1.nc\"" "outfile=\"tmp2.nc\"" "lat_out=(/$lat_out/)" "plev_out=(/$plev_out/)" \
+    $interpncl; cdo setzaxis,$cwd/$zaxisdes tmp2.nc $fclimate; rm tmp?.nc
+  # NCAP interpolation; must loop over other dimensions manually
+  # echo "Interpolating horizontally with ncap2 GSL function."
+  # cat > interp.nco << EOF
+  # defdim("eralat",$numeralat); // declare new dimension
+  # eralat[\$eralat]={$eralat}; // destination latitude
+  # gsl_interp_linear(&func, lat, t);
+  # t_dest=gsl_spline_eval(func, eralat); // interpolate to new data
+  # EOF
+  # ncap2 -S interp.nco $fclimate tmp.nc # holds interpolated data
 }
 
 #########################################i#######################################
@@ -154,7 +177,7 @@ function EOFs() {
     region=$1 # the region
     level=$2 # the level
     [[ -z $region || -z $level ]] && echo "ERROR: EOF function needs two arguments." && return 1
-    [[ ! ",$eralevels," =~ ",$level," ]] && echo "ERROR: Level is not an ERA-Interim level. Please choose from ${levels}." && return 1
+    [[ ! ",$plev_out," =~ ",$level," ]] && echo "ERROR: Level is not an ERA-Interim level. Please choose from ${levels}." && return 1
     case $region in
       NH) selregion="-sellonlatbox,-180,180,0,90" ;; # north-hemisphere selection
       SH) selregion="-sellonlatbox,-180,180,-90,0" ;; # south-hemisphere selection
