Massive changes to run scripts. Now everything is much more self-contained. Batch script alone sets the namelist and diag table; the run script naively reads this and runs the model (with a few run-specific settings). The run, process, and post-process scripts now all accept flags -- no more tracking global variables.

diff --git a/drycore_compile b/drycore_compile
--- a/drycore_compile
+++ b/drycore_compile
@@ -4,82 +4,67 @@
 #------------------------------------------------------------------------------
 # Fix host-specific settings
 #------------------------------------------------------------------------------
-expname=hs
+expname=pk
 hostname=${HOSTNAME%%.*} # trims e.g. monde.atmos.colostate.edu
-if [[ "$hostname" == "olbers" ]]; then # netcdf-c lib is separate from netcdf-fortran lib
-  include=(/usr/local/mpich3/include /usr/local/netcdf4/include /usr/local/netcdf4-pgi/include)
-  links=(/usr/local/mpich3/lib /usr/local/netcdf4/lib /usr/local/netcdf4-pgi/lib /usr/local/hdf5/lib)
-  root=/home/ldavis/gfdl
-  pgi=/opt/pgi/linux86-64/2017/bin
-  fix=' -lcurl'
-elif [[ "$hostname" == "gauss" ]]; then # libs are together; slightly different naming (not sure why mpich and hdf5 have
-       # 'pgi' and 'gcc' options, should be copies; only netcdf-fortran can be compiled with either)
-  include=(/usr/local/mpich3-pgi /usr/local/netcdf4-pgi/include)
-  links=(/usr/local/mpich3-pgi/lib /usr/local/netcdf4-pgi /usr/local/hdf5-pgi/lib)
-  root=/home/ldavis/gfdl
-  pgi=/opt/pgi/linux86-64/2016/bin
-  fix=' -lcurl'
-elif [[ "$hostname" == "monde" ]]; then # everything is bunched together
-  include=(/usr/include/mpich-x86_64)
-  links=(/usr/lib64/mpich/lib)
-  root=/home/ldavis/gfdl
-  pgi=/opt/pgi/linux86-64/17.10/bin
-  fix=' -lcurl'
-elif [[ "$hostname" == "euclid" ]]; then # everything is bunched together
-  include=(/usr/local/include)
-  links=(/usr/local/lib)
-  root=/birner-home/ldavis/gfdl
-  pgi=/opt/pgi/linux86-64/2013/bin
-  fix=''
-else
-  echo "Error: Unknown host, must configure library and binary locations before running."
-  exit
-fi
+case ${HOSTNAME%%.*} in
+  olbers) # netcdf-c lib is separate from netcdf-fortran lib
+    include=(/usr/local/mpich3/include /usr/local/netcdf4/include /usr/local/netcdf4-pgi/include)
+    links=(/usr/local/mpich3/lib /usr/local/netcdf4/lib /usr/local/netcdf4-pgi/lib /usr/local/hdf5/lib)
+    root=/home/ldavis/gfdl
+    pgi=/opt/pgi/linux86-64/2017/bin
+    # fix=' -lcurl' # not sure why needed this, probably fake news
+    ;;
+  gauss) # libs are together; slightly different naming (not sure why mpich and hdf5 have
+         # 'pgi' and 'gcc' options, should be copies; only netcdf-fortran can be compiled with either)
+    include=(/usr/local/mpich3-pgi /usr/local/netcdf4-pgi/include)
+    links=(/usr/local/mpich3-pgi/lib /usr/local/netcdf4-pgi /usr/local/hdf5-pgi/lib)
+    root=/home/ldavis/gfdl
+    pgi=/opt/pgi/linux86-64/2016/bin
+    # fix=' -lcurl'
+    ;;
+  monde)
+    include=(/usr/include/mpich-x86_64)
+    links=(/usr/lib64/mpich/lib)
+    root=/home/ldavis/gfdl
+    pgi=/opt/pgi/linux86-64/17.10/bin
+    # fix=' -lcurl'
+    ;;
+  euclid) # everything is bunched together
+    include=(/usr/local/include)
+    links=(/usr/local/lib)
+    root=/birner-home/ldavis/gfdl
+    pgi=/opt/pgi/linux86-64/2013/bin
+    # fix=''
+    ;;
+  *) echo "Error: Unknown host, must configure library and binary locations before running." && exit 1 ;;
+esac
 #------------------------------------------------------------------------------
 # Build executable model code and post-processing tool
 #------------------------------------------------------------------------------
-execdir=$(pwd)/exe_${expname}_${hostname}      # where code is compiled and executable is created
-src=$root/src_$expname                         # path to directory containing model source code
+# Definitions
+execdir=${expname}_${HOSTNAME%%.*}      # where code is compiled and executable is created
+src=$root/src                                  # path to directory containing model source code
 mkmf=$root/bin/mkmf                            # path to executable mkmf
 mkmftemplate=$root/bin/mkmf.template           # template of most basic settings
 mppnsource=$root/postprocessing/mppnccombine.c # source code
-pathnames=$src/path_names                      # stored in source directory
+pathnames=$src/path_names_$expname             # stored in source directory
 cppdefs="-Duse_libMPI -Duse_netCDF"            # not sure what this does
 flags_links="${links[@]/#/-L}"                 # search these paths for library files
 flags_include="${include[@]/#/-I}"             # include flags
 flags_libs="-lmpl -lmpich -lfmpich -lmpichf90 -lnetcdff -lnetcdf -lhdf5_hl -lhdf5 -lm -lz $fix" # for mppnccombine
 # Make sure necessary things tools are in path
-if [ ! -d $execdir ]; then
-  mkdir $execdir
-else
-  # echo "WARNING: Removing old compiled source..."
-  echo "Warning: Leaving old compiled source..."
-fi
-if [ ! -r $pathnames ]; then
-  echo "Error: Could not find path_names file $pathnames."
-  exit
-fi
-if [ ! -d $src ]; then
-  echo "Error: Could not find source code directory $src."
-  exit
-fi
-if [ ! -r $mppnsource ]; then
-  echo "Error: Could not find mppnccombine source code."
-  exit
-fi
-if [ ! -r $mkmftemplate ]; then
-  echo "Error: Could not find mppnccombine source code."
-  exit
-fi
-if [ ! -r $mkmf ]; then
-  echo "Error: Could not find Makefile-generating utility $mkmf."
-  exit
-fi
+[ ! -d $execdir ]      && mkdir $execdir || echo "Warning: Leaving old compiled source."
+[ ! -d $src ]          && echo "Error: Could not find source code directory $src."        && exit 1
+[ ! -r $pathnames ]    && echo "Error: Could not find path_names file $pathnames."        && exit 1
+[ ! -r $mppnsource ]   && echo "Error: Could not find mppnccombine source code."          && exit 1
+[ ! -r $mkmftemplate ] && echo "Error: Could not find mppnccombine source code."          && exit 1
+[ ! -r $mkmf ]         && echo "Error: Could not find Makefile-generating utility $mkmf." && exit 1
+#------------------------------------------------------------------------------#
 # Create mppnccombine; should supply with same libraries supplied to model executable through its makefile
 # $pgi/pgcc -O -o $mppnccombine -I$netcdfc/include -I$mpich/include $mppnsource $flags_links $flags_libs
 time=$(date +%s)
 echo "Generating mppnccombine executable..."
-$pgi/pgcc -O -o mppnccombine $flags_include $mppnsource $flags_links $flags_libs
+$pgi/pgcc -O -o mppnccombine.x $flags_include $mppnsource $flags_links $flags_libs
   # -O[level] = set optimization level; sets to 2 if number not specified
   # -o file = use this file as name of executable
   # -Idirectory = add directory to compiler search path; these are 'header' files
@@ -87,6 +72,7 @@ $pgi/pgcc -O -o mppnccombine $flags_include $mppnsource $flags_links $flags_libs
   # -llibrary = load lib<library>.a from the standard library directory (supplied by L?)
   # ...the mpllibs in MPICH seem to only have .so instead of .a ... not sure what that means
   # ...also it seems there is no libm.a or libz.a
+#------------------------------------------------------------------------------#
 # Build makefile template (assumes pgi bin is on $PATH)
 cd $execdir # move to source directory
 cat > mkmf.template << DELIM
@@ -99,6 +85,7 @@ LDFLAGS = $flags_links $flags_libs -Mmpi=mpich
 LIST = -Mlist
 DELIM
 cat $mkmftemplate >> mkmf.template # appends provided template to custom defs
+#------------------------------------------------------------------------------#
 # Create makefile
 echo "Generating Makefile..."
 cat mkmf.template
@@ -109,6 +96,7 @@ $mkmf -p fms.x -t mkmf.template -c "$cppdefs" -a $src $pathnames \
   # -c = list of 'cpp #define's passed to source files (what?)
   # -a = abspath, attaches 'abspath' (here, $src) to the FRONT of RELATIVE paths to the source file
   # args (all the later stuff) = list of directories/files to be searched for targets and dependencies
+#------------------------------------------------------------------------------#
 # Compile source
 echo "Compiling source code..."
 make -f Makefile
diff --git a/process b/process
--- a/process
+++ b/process
@@ -22,78 +22,69 @@ function nclcheck() { # input log file as argument
   return $? # return exit code; good status means we found error, bad status means we found nothing
     # ignore ^warning: because these will also happen if we have a systemfunc error possibly
 }
+# Parse input flags
+nomove=false    # keep data in original folder, instead of moving to ../netcdf? useful for testing
+keepxyz=false    # keep original "full" results?
+resume=false    # process old "full" files?
+cdointerp=false # slower than NCO
+while [ $# -gt 0 ]; do
+  case $1 in
+    -q|--quit) echo "Skipping processing." && exit 0 ;; # do nothing and quit (see drycore_run)
+    -k|--keep)       keepxyz=true     ;; # whether to keep longitudinal data
+    -r|--resume)     resume=true     ;; # process old results
+    -m|--no-move)    nomove=true     ;; # if true, keep all intermediate files
+    -c|--cdo-interp) cdointerp=false ;; # interpolate with CDO instead of NCL? much slower during testing (see notes)
+    *) echo "Error: Unknown flag \"$1\"." && exit 1 ;;
+  esac
+  shift # shift by one
+done
 # Global vars
-t0=$(date +%s)      # starting time
-nckeep=$1           # whether to keep longitudinal data
-testing=$2          # check if testing mode enabled; if true, keep all intermediate files
-basedir=${0%/*}     # same location as this file; trim filename from right
-interpwithcdo=false # interpolate with CDO instead of NCL? much slower during testing (see notes)
-hostname=${HOSTNAME%%.*} # trim e.g. monde.atmos.colostate.edu --> monde
-mppnccombine=$basedir/mppnccombine # combine; needs to have been compiled here
-interpcdo=$basedir/process_interp     # interpolate with CDO
-interpncl=$basedir/process_interp.ncl # interpolate with NCL, automatic iteration
-# interpncl=$basedir/process_interpex.ncl # interpolate with NCL, explicitly interpolate select variables
-params=$basedir/process_params.ncl    # params with NCL
-basics=$basedir/process_basic     # zonal means and flux terms with CDO
-lorenz=$basedir/process_energy.ncl  # eddy and mean Lorenz energy cycle terms with NCL
-# lorenz=$basedir/process_lorenz    # Lorenz energy cycle terms with CDO
-# energy=$basedir/process_energy    # Lorenz energy cycle terms with CDO
+t0=$(date +%s)                    # starting time
+bin=${0%/*}                       # same location as this file; trim filename from right
+interpcdo=$bin/process_interp     # interpolate with CDO
+interpncl=$bin/process_interp.ncl # interpolate with NCL, automatic iteration
+mppnccombine=$bin/mppnccombine.x  # combine; needs to have been compiled here
+params=$bin/process_params.ncl    # params with NCL
+basics=$bin/process_basic         # zonal means and flux terms with CDO
+lorenz=$bin/process_energy.ncl    # eddy and mean Lorenz energy cycle terms with NCL
+process3d=$bin/process_3d         # 3d processing with CDO and stuff
+# lorenz=$bin/process_lorenz      # Lorenz energy cycle terms with CDO
+# energy=$bin/process_energy      # Lorenz energy cycle terms with CDO
 # Double check some stuff
-if [ -z "$nckeep" ]; then
-  echo "Error: Must pass bash true/false whether you want to keep original longitude-res data."
-  exit 999
-fi
-if [ -z "$testing" ]; then
-  echo "Error: Must pass bash true/false whether you want to use testing mode."
-  exit 999
-fi
-if ! hash ncl 2>/dev/null; then
-  echo "Error: NCL is not in $PATH."
-  exit 999
-fi
-if ! hash cdo 2>/dev/null; then
-  echo "Error: CDO is not in $PATH."
-  exit 999
-fi
-if ! hash ncrename 2>/dev/null || ! hash ncks 2>/dev/null; then
-  echo "Error: NCO is not in $PATH."
-  exit 999
-fi
-if [ ! -x $mppnccombine ]; then
-  echo "Error: The mpp combine executable $mppnccombine is missing."
-  exit 999
-fi
-if [ ! -x $basics ]; then
-  echo "Error: The script $basics is missing."
-  exit 999
-fi
-if [ ! -x $lorenz ]; then
-  echo "Error: The script $lorenz is missing."
-  exit 999
-fi
-if [ ! -r $interpncl ]; then
-  echo "Error: The script $interpncl is missing."
-  exit 999
-fi
+[ ! -x $basics ]        && echo "Error: The script \"$basics\" is missing."                   && exit 127
+[ ! -x $lorenz ]        && echo "Error: The script \"$lorenz\" is missing."                   && exit 127
+[ ! -r $interpncl ]     && echo "Error: The script \"$interpncl\" is missing."                && exit 127
+[ ! -x $mppnccombine ]  && echo "Error: The mpp combine executable $mppnccombine is missing." && exit 127
+! hash ncl 2>/dev/null  && echo "Error: NCL is not in $PATH."                                 && exit 127
+! hash cdo 2>/dev/null  && echo "Error: CDO is not in $PATH."                                 && exit 127
+! hash ncks 2>/dev/null && echo "Error: NCO is not in $PATH."                                 && exit 127
 
 ################################################################################
 # Combine the files produced in parallel
 # And check if any netCDF output; see: https://stackoverflow.com/q/2937407/4970632
-# if ! compgen -G *.nc > /dev/null; then
-# if [ ! -n "$(find . -maxdepth 1 -name "*.nc" -print -quit)" ]; then
-# if ! stat -t *.nc > /dev/null 2>&1; then
-t=$(date +%s)
-for ncfile in *.nc.0000; do
-  if [ "$ncfile" == "*.nc.0000" ]; then # make sure nullglob turned off
-    echo "Error: No output netcdf files found."
-    exit 1 # tell invoking shell that previous model failed
-  fi # then combine, if any exist
-  files=(${ncfile%%.*}.nc*) # put into array
-  echo "Combining files: ${files[@]} into ${ncfile%%.*}.nc"
-  $mppnccombine -r ${ncfile%%.*}.nc ${files[@]}
-done # -r flag says to remove the decomposed .0000 files after they are combined
-  # first arg is output, remaining args are all input
-echo "  * Time for combining files: $(($(date +%s) - $t))s."
+if $resume; then
+  # Will use existing _full.nc XYZ resolution files for getting the XY files
+  echo "Using previous model results for getting XY files."
+  if $nomove; then
+    ncfiles=(*_full.nc)
+  else
+    ncfiles=(../netcdf/*_full.${PWD##*/}.nc)
+  fi
+  [[ "$ncfiles" =~ "*" ]] && echo "Error: XYZ resolution file was not found."
+else
+  # Will process the raw model output, then get the _full XYZ files and XY files from result
+  t=$(date +%s)
+  for ncfile in *.nc.0000; do # for each output filename
+    [[ "$ncfile" =~ "*" ]] && echo "Error: No netcdf files found." && exit 1 # make sure nullglob turned off
+    files=(${ncfile%%.*}.nc*) # put into array
+    echo "Combining files: ${files[@]} into ${ncfile%%.*}.nc"
+    $mppnccombine -r ${ncfile%%.*}.nc ${files[@]}
+  done # -r flag says to remove the decomposed .0000 files after they are combined; arg 1 is output, arg 2-N is input
+  echo "  * Time for combining files: $(($(date +%s) - $t))s."
+  # Initialize directory for output
+  [ ! -d ../netcdf ] && mkdir ../netcdf # make directory if doesn't exist
+  ncfiles=(*.nc) # each output file
+fi
 
 ################################################################################
 # THE STDOUT OF THESE LINES IS AN OVERVIEW; SEPARATE STDOUTS FOR CDO/NCL STEPS
@@ -104,15 +95,14 @@ echo "  * Time for combining files: $(($(date +%s) - $t))s."
 #   isaveraged="print(isfilevar(addfile(\"$ncfile\",\"r\"),\"time_bounds\"))"
 # * [ $(ncl -Q -n <<< "$isaveraged") == "False" ] # NCL test if averaged
 # * [[ ! " $(ncvarlist $ncfile) " =~ " time_bounds " ]] # NCO test if averaged
-[ ! -d ../netcdf ] && mkdir ../netcdf # make directory if doesn't exist
-for ncfile in *.nc; do
-  # Determine file names
-  if $testing; then # special names, and keep in same folder
-    outfile="${ncfile%%.*}_summary.nc" # longitude-averaged data
-    origfile="${ncfile%%.*}_full.nc" # original data
+for ncfile in ${ncfiles[@]}; do
+  # Ouput file names
+  if $nomove; then # special names, and keep in same folder
+    xyfile="${ncfile%%.*}_summary.nc" # longitude-averaged data
+    xyzfile="${ncfile%%.*}_full.nc" # original data
   else
-    outfile="../netcdf/${ncfile%%.*}_summary.${PWD##*/}.nc" # longitude-averaged data
-    origfile="../netcdf/${ncfile%%.*}_full.${PWD##*/}.nc" # original data
+    xyfile="../netcdf/${ncfile%%.*}_summary.${PWD##*/}.nc" # longitude-averaged data
+    xyzfile="../netcdf/${ncfile%%.*}_full.${PWD##*/}.nc" # original data
   fi
   # Apply some simple modifications to attributes
   ncrename -d pfull,mlev $ncfile &>/dev/null # mlev is the ECHAM convention, needed for CDO interpolation
@@ -122,32 +112,35 @@ for ncfile in *.nc; do
   ncatted -O -a bounds,mlev,o,c,"ilev" $ncfile
   ncatted -O -a long_name,udamp,o,c,"Rayleigh damping of zonal wind" $ncfile
   ncatted -O -a long_name,vdamp,o,c,"Rayleigh damping of meridional wind" $ncfile
+
   ############################################################################
-  interpfile=${ncfile%%.*}_interp.nc
-  # 1) Interpolate the data to pressure levels
-  # a) Use CDO for interpolation
-  t=$(date +%s)
-  if $interpwithcdo; then
-    echo "Interpolating with CDO..."
-    $interpcdo $ncfile $interpfile &>log.interp # that simple babe
-    [ $? != 0 ] && echo "Error: Something failed during CDO interpolation." && exit $?
-    ! $testing && rm interp?.nc
-  # b) Use NCL vint2hp_ecmwf for interpolation
-  else
-    echo "Interpolating with NCL..." # -Q = no banner, -n = do not enumerate print statements
-    ncl -n -Q "filename=\"$ncfile\"" "outfile=\"$interpfile\"" $interpncl &>log.interp #2> /dev/null
-    if nclcheck log.interp || [ ! -r $interpfile ]; then
-      echo "Error: Something failed during NCL interpolation." && exit 2
+  if ! $resume; then # data already interpolated
+    # 1) Interpolate the data to pressure levels
+    interpfile=${ncfile%%.*}_interp.nc
+    # a) Use CDO for interpolation
+    t=$(date +%s)
+    if $cdointerp; then
+      echo "Interpolating with CDO..."
+      $interpcdo $ncfile $interpfile &>log.interp # that simple babe
+      [ $? != 0 ] && echo "Error: Something failed during CDO interpolation." && exit $?
+      ! $nomove && rm interp?.nc
+    # b) Use NCL vint2hp_ecmwf for interpolation
+    else
+      echo "Interpolating with NCL..." # -Q = no banner, -n = do not enumerate print statements
+      ncl -n -Q "filename=\"$ncfile\"" "outfile=\"$interpfile\"" $interpncl &>log.interp #2> /dev/null
+      if nclcheck log.interp || [ ! -r $interpfile ]; then
+        echo "Error: Something failed during NCL interpolation." && exit 2
+      fi
     fi
+    # Standardize attributes
+    ncatted -a edges,lon,d,, -a edges,lat,d,, \
+      -a axis,lon,o,c,"X" -a axis,lat,o,c,"Y" -a axis,plev,o,c,"Z" \
+      -a long_name,plev,o,c,"pressure level" -a units,plev,o,c,"mb" -a bounds,plev,o,c,"plev_bnds" \
+      -a long_name,lat,o,c,"latitude" -a units,lat,o,c,"degrees_north" \
+      -a long_name,lon,o,c,"longitude" -a units,lon,o,c,"degrees_east" $interpfile
+    $nomove && ncfile=$interpfile || mv $interpfile $ncfile # move old file on top of new file
+    echo "  * Time for interpolation: $(($(date +%s) - $t))s."
   fi
-  # Standardize attributes
-  ncatted -a edges,lon,d,, -a edges,lat,d,, \
-    -a axis,lon,o,c,"X" -a axis,lat,o,c,"Y" -a axis,plev,o,c,"Z" \
-    -a long_name,plev,o,c,"pressure level" -a units,plev,o,c,"mb" -a bounds,plev,o,c,"plev_bnds" \
-    -a long_name,lat,o,c,"latitude" -a units,lat,o,c,"degrees_north" \
-    -a long_name,lon,o,c,"longitude" -a units,lon,o,c,"degrees_east" $interpfile
-  $testing && ncfile=$interpfile || mv $interpfile $ncfile # move old file on top of new file
-  echo "  * Time for interpolation: $(($(date +%s) - $t))s."
 
   # ##############################################################################
   # # Add some parameters to the longitude-latitude file with NCL
@@ -160,21 +153,20 @@ for ncfile in *.nc; do
   # echo "  * Time for getting extra parameters with NCL: $(($(date +%s) - $t))s."
 
   ##############################################################################
-  # 2) Get extra stuff with CDO commands (either simple zonal mean, or add some stuff)
-  # Some of these require the extra variables output by NCL; also meridional flux
-  # terms rely on NCL having set poleward==positive in each hemisphere
+  # 2) Get 2D resolution parameters
+  # First the CDO commands
   # t=$(date +%s)
-  echo "Getting basic terms..."
+  echo "Getting CDO 2D parameters..."
   $basics $ncfile &>log.basic &
   pbasics=$!
   # [ $? != 0 ] && echo "Error: Something failed while getting basic terms." && exit 3
   # echo "  * Time for getting basic terms with CDO: $(($(date +%s) - $t))s."
   ##############################################################################
-  # 3) Get energy terms in another file
+  # Next the NCL commands; used to get energy terms
   # Some of these require the extra variables output by NCL; also meridional flux
   # terms rely on NCL having set poleward==positive in each hemisphere
   # t=$(date +%s)
-  echo "Getting Lorenz energy cycle terms..."
+  echo "Getting NCL 2D parameters..."
   ncl -n -Q "filename=\"$ncfile\"" $lorenz &>log.lorenz &
   plorenz=$!
   # if nclcheck log.lorenz; then
@@ -182,59 +174,58 @@ for ncfile in *.nc; do
   # fi
   # echo "  * Time for getting Lorenz energy terms with NCL: $(($(date +%s) - $t))s."
   ##############################################################################
-  # Manage background processes
-  # First the basic term
+  # Manage the two background processes
   wait $pbasics # wait for basic terms
-  [ $? != 0 ] && echo "Error: Something failed while getting basic terms." && exit 3
+  [ $? != 0 ] && echo "Error: Something failed while getting CDO parameters." && exit 3
   twait=$(tail -1 log.basic | sed 's/[^0-9]*//g')
-  echo "  * Time for getting basic terms with CDO: ${twait}s."
-  # Next the Lorenz terms
+  echo "  * Time for getting 2D parameters with CDO: ${twait}s."
   wait $plorenz # wait for Lorenz terms
   if nclcheck log.lorenz; then
-    echo "Error: Something failed getting extra parameters with NCL." && exit 4
+    echo "Error: Something failed while getting NCL parameters." && exit 4
   fi
   twait=$(tail -1 log.lorenz | sed 's/[^0-9]*//g')
-  echo "  * Time for getting Lorenz energy terms with NCL: ${twait}s."
+  echo "  * Time for getting 2D parameters with NCL: ${twait}s."
 
   ##############################################################################
-  # 4) Tidy up
+  # 4) Tidy up, and get 2D terms
   t=$(date +%s)
-  echo "Merging all the terms into one file..."
+  echo "Merging the CDO and NCL parameters into one file..."
   # First add back longitudes to NCL calculated terms
   # Hard/annoying/verbose to fix this in NCL so do it here
   for f in energy??.nc; do # absolutely necessary for CDO to detect plev as vertical axis, and need singleton longitude
     cdo -s -setgrid,basic1.nc $f tmp.nc; mv tmp.nc $f # so ugly... kill me...
   done
   # Next apply merge
-  cdo -O -s -merge basic?.nc energy??.nc $outfile # will raise errors because edges were deleted, but still referenced by attributes
-  ncks -O $outfile $outfile # clever hack; just *alphabetizes* the variables in file, and very fast
-  echo "  * Time for merging all the terms into one file: $(($(date +%s) - $t))s."
+  cdo -O -s -merge basic?.nc energy??.nc $xyfile # will raise errors because edges were deleted, but still referenced by attributes
+  ncks -O $xyfile $xyfile # clever hack; just *alphabetizes* the variables in file, and very fast
+  echo "  * Time for merging into one file: $(($(date +%s) - $t))s."
   # Then remove the temporary files
-  ! $testing && rm basic?.nc energy??.nc
-  if $nckeep; then
-    # Keep the old file
-    # Also get divergence, vorticity, streamfunction, and velocity potential
-    t=$(date +%s)
-    echo "Keeping longitude-resolution file and calculating extra terms..."
-    cdo -O -s -uv2dv -selname,u,v $ncfile dv0.nc 1>/dev/null # gets spectral coefs for vor and div
-    cdo -O -s -invertlat -sp2gp -dv2ps dv0.nc dv1.nc 1>/dev/null # default names are fine
-    cdo -O -s -chname,sd,div,svo,vor -invertlat -sp2gp dv0.nc dv2.nc # better names
-    ncap2 -O -s '*f[$lat] = 2*7.292e-5*sin(lat*3.14159/180); absvor = vor+f' dv2.nc dv2.nc
-      # get absolute vorticity; asterisk means this is a "RAM" variable, not saved in final output
-    if [ ! -r dv0.nc ] || [ ! -r dv1.nc ] || [ ! -r dv2.nc ]; then
-      echo "Warning: Could not get the vorticity/divergence/streamfunction terms."
-      ! $testing && rm dv?.nc # remove any that may exist
-      mv $ncfile $origfile
+  ! $nomove && rm basic?.nc energy??.nc
+  if ! $resume; then
+    if $nomove || $keepxyz; then
+      # Keep the old file
+      # Also get divergence, vorticity, streamfunction, and velocity potential
+      t=$(date +%s)
+      echo "Keeping XYZ file and calculating extra terms..."
+      cdo -O -s -uv2dv -selname,u,v $ncfile dv0.nc 1>/dev/null          # gets spectral coefs for vor/div from Gaussian grid of u/v
+      cdo -O -s -delname,velopot -invertlat -sp2gp -dv2ps dv0.nc dv1.nc # spectral vor/div to spectral streamfunc/velocity pot; throw out the latter
+      cdo -O -s -chname,sd,div,svo,vor -invertlat -sp2gp dv0.nc dv2.nc  # better names
+      ncap2 -O -s '*f[$lat] = 2*7.292e-5*sin(lat*3.14159/180); absvor = vor+f' dv2.nc dv2.nc # tack on absolute vorticity
+        # get absolute vorticity; asterisk means this is a "RAM" variable, not saved in final output
+      if [ ! -r dv0.nc ] || [ ! -r dv1.nc ] || [ ! -r dv2.nc ]; then
+        echo "Warning: Could not get the vir/div/streamfunc terms."
+        mv $ncfile $xyzfile
+      else
+        cdo -O -s -merge $ncfile dv1.nc dv2.nc $xyzfile
+        ! $nomove && rm $ncfile
+      fi
+      ! $nomove && rm dv?.nc # remove any that may exist
+      echo "  * Time for getting extra div/vor/streamfunc terms from original file: $(($(date +%s) - $t))s."
     else
-      cdo -O -s -merge $ncfile dv1.nc dv2.nc $origfile
-      ! $testing && rm dv?.nc
-      ! $testing && rm $ncfile
+      # Delete the old file
+      echo "Removing XYZ file..."
+      ! $nomove && rm $ncfile # simple
     fi
-    echo "  * Time for getting extra div/vor/streamfunc terms from original file: $(($(date +%s) - $t))s."
-  else
-    # Delete the old file
-    echo "Removing longitude-resolution file..."
-    ! $testing && rm $ncfile # simple
   fi
 done
 # Finally, echo time of finish
