Organize, bug fixes, readme

diff --git a/drycore_compile b/drycore_compile
--- a/drycore_compile
+++ b/drycore_compile
@@ -1,56 +1,94 @@
 #!/bin/bash
 # Script for compiling fortran source code, as user has specified. Then the runscript will integrate
 # it forward, produce output, etc.
+# pgcc or pgif90 flags:
+#   -O[level] = set optimization level; sets to 2 if number not specified
+#   -o file = use this file as name of executable
+#   -I directory = add directory to compiler search path; these are 'header' files
+#   -L directory = change the directory in which "linker" searches for libraries
+#   -l library = load lib<library>.a from the standard library directory (supplied by L?)
+#   -Ktrap=opt1,opt2,... = detect floating point
+# specific, default flags from Nick's version for running on single server:
+#   -r8 = interpret real variables as double
+#   -pc 64 = double-precision 64-bit calculations, needed
+#   -tp=sandrybridge = optimize for sandybridge XEON (E5) processors; if not on Euclid, change this to reflect your CPU core architecture
+#   -Kieee = more accurate division with less rounding error
+#   -Mmpi=mpich = link with MPICH library
+# mkmf flags:
+#   -p = program (name of final target)
+#   -t = template (list of MACROS/COMMANDS that get appended to beginning of final Makefile)
+#   -c = list of 'cpp #define's passed to source files, as -D flags (what?)
+#   -a = abspath, attaches 'abspath' (here, $src) to the FRONT of RELATIVE paths to the source file
+# args (all the later stuff) = list of directories/files to be searched for targets and dependencies
 #------------------------------------------------------------------------------
-# Fix host-specific settings
+# Initial stuff
 #------------------------------------------------------------------------------
+# Variables
+# Maybe need -lhdf5_hl, -lhdf5, -lmpichf90, -lmpl, -lm, -lz, but not sure
+execdir=./drycore-${HOSTNAME%%.*}   # where code is compiled and executable is created
+flags_optimization='-O3'            # O2 or O3? more optimization can actually be *slower*, but GFDL default was O3 so maybe not; https://stackoverflow.com/a/19985801/4970632
+flags_float='-Ktrap=fp'             # add =flag1,flag2,... for options; controls floating point exceptions; http://www.dartmouth.edu/~rc/HPC/man/pgf90.html
+flags_fort='-lnetcdff -lnetcdf'     # for mppnccombine
+flags_ld='-Mmpi=mpich'              # special 'pgflags', adds flags -L$MPILIB -lfmpich -lmpich; http://www.dartmouth.edu/~rc/HPC/man/pgf90.html
+cppdefs='-Duse_libMPI -Duse_netCDF' # not sure what this does
+# Use Intel MPI or openmpi instead of default mpt
+# See: https://www2.cisl.ucar.edu/resources/computational-systems/cheyenne/running-jobs/intel-mpi-and-open-mpi
+# This actually worked! Really necessary!
+module load intel &>/dev/null
+module load netcdf &>/dev/null
+module load impi &>/dev/null
+# Host-specific settings
 case ${HOSTNAME%%.*} in
-  olbers) # netcdf-c lib is separate from netcdf-fortran lib
-    include=(/usr/local/mpich3/include /usr/local/netcdf4/include /usr/local/netcdf4-pgi/include)
-    links=(/usr/local/mpich3/lib /usr/local/netcdf4/lib /usr/local/netcdf4-pgi/lib /usr/local/hdf5/lib)
-    root=/home/ldavis/drycore-gfdl
-    pgi=/opt/pgi/linux86-64/2017/bin
-    # fix=' -lcurl' # not sure why needed this, probably fake news
-    ;;
-  gauss) # libs are together; slightly different naming (not sure why mpich and hdf5 have
-         # 'pgi' and 'gcc' options, should be copies; only netcdf-fortran can be compiled with either)
-    include=(/usr/local/mpich3-pgi /usr/local/netcdf4-pgi/include)
-    links=(/usr/local/mpich3-pgi/lib /usr/local/netcdf4-pgi /usr/local/hdf5-pgi/lib)
-    root=/home/ldavis/drycore-gfdl
-    pgi=/opt/pgi/linux86-64/2016/bin
-    # fix=' -lcurl'
-    ;;
-  monde)
-    include=(/usr/include/mpich-x86_64)
+  # olbers) # netcdf-c lib is separate from netcdf-fortran lib
+  #   include=(/usr/local/mpich3/include /usr/local/netcdf4/include /usr/local/netcdf4-pgi/include)
+  #   links=(/usr/local/mpich3/lib /usr/local/netcdf4/lib /usr/local/netcdf4-pgi/lib /usr/local/hdf5/lib)
+  #   root=/home/ldavis/gfdl-drycore
+  #   pgi=/opt/pgi/linux86-64/2017/bin
+  # ;; gauss) # libs are together; slightly different naming (not sure why mpich and hdf5 have 'pgi' and 'gcc' options, should be copies; only netcdf-fortran can be compiled with either)
+  #   include=(/usr/local/mpich3-pgi /usr/local/netcdf4-pgi/include)
+  #   links=(/usr/local/mpich3-pgi/lib /usr/local/netcdf4-pgi /usr/local/hdf5-pgi/lib)
+  #   root=/home/ldavis/gfdl-drycore
+  #   pgi=/opt/pgi/linux86-64/2016/bin
+  cheyenne*) # found via: for var in $(variables | grep -i netcdf); do echo ${var}: ${!var}; done
+    # Basic libraries, with links to fortran compilers
+    echo Compiler: $NETCDF
+    links=($NETCDF/lib)
+    include=($NETCDF/include)
+    root=$HOME/gfdl-drycore
+    execdir=./drycore-cheyenne/ # usually cheyenneN, where N is login node number
+    fortran=mpif90 # or ifort?
+    cpp=mpicc # or icc? why use a different compiler, can't we supply normal one with mpi flags?
+    fortran=mpiifort
+    cpp=mpiicc
+    # Cheyenne uses a compiler wrapper mpif90 that handles all mpi flags
+    flags_float=''
+    flags_fort='-lnetcdff -lnetcdf' # do not need much
+    flags_ld='-qopenmp'
+    # Load modules? Or just run with correct modules installed already.
+    # module load intel
+  ;; monde)
     links=(/usr/lib64/mpich/lib)
-    root=/home/ldavis/drycore-gfdl
-    pgi=/opt/pgi/linux86-64/17.10/bin
-    # fix=' -lcurl'
-    ;;
-  euclid) # everything is bunched together
+    include=(/usr/include/mpich-x86_64)
+    root=$HOME/gfdl-drycore
+    fortran=pgf90
+    cpp=pgcc
+  ;; euclid) # everything is bunched together
     include=(/usr/local/include)
     links=(/usr/local/lib)
-    root=/birner-home/ldavis/drycore-gfdl
-    pgi=/opt/pgi/linux86-64/2013/bin
-    # fix=''
-    ;;
-  *) echo "Error: Unknown host, must configure library and binary locations before running." && exit 1 ;;
+    root=/birner-home/ldavis/gfdl-drycore
+    fortran=pgf90
+    cpp=pgcc
+  ;; *) echo "Error: Unknown host, must configure library and binary locations before running." && exit 1 ;;
 esac
-
-#------------------------------------------------------------------------------
-# Build executable model code and post-processing tool
-#------------------------------------------------------------------------------
-# Definitions
+# Flags
+flags_links="${links[@]/#/-L}"                 # search these paths for library files
+flags_include="${include[@]/#/-I}"             # include flags
+# Directories
 src=$root/src                                  # path to directory containing model source code
-execdir=./drycore-${HOSTNAME%%.*}                        # where code is compiled and executable is created
 pathnames=$src/path_names_new                  # change this to pick different blocks of code
 mkmf=$root/bin/mkmf                            # path to executable mkmf
 mkmftemplate=$root/bin/mkmf.template           # template of most basic settings
 mppnsource=$root/postprocessing/mppnccombine.c # source code
-cppdefs="-Duse_libMPI -Duse_netCDF"            # not sure what this does
-flags_links="${links[@]/#/-L}"                 # search these paths for library files
-flags_include="${include[@]/#/-I}"             # include flags
-flags_libs="-lmpl -lmpich -lfmpich -lmpichf90 -lnetcdff -lnetcdf -lhdf5_hl -lhdf5 -lm -lz $fix" # for mppnccombine
 # Make sure necessary things tools are in path
 [ ! -d $execdir ]      && mkdir $execdir || echo "Warning: Leaving old compiled source."
 [ ! -d $src ]          && echo "Error: Could not find source code directory $src."        && exit 1
@@ -58,41 +96,37 @@ flags_libs="-lmpl -lmpich -lfmpich -lmpichf90 -lnetcdff -lnetcdf -lhdf5_hl -lhdf
 [ ! -r $mppnsource ]   && echo "Error: Could not find mppnccombine source code."          && exit 1
 [ ! -r $mkmftemplate ] && echo "Error: Could not find Makefile template."          && exit 1
 [ ! -r $mkmf ]         && echo "Error: Could not find Makefile-generating utility $mkmf." && exit 1
+
+#------------------------------------------------------------------------------
+# Build executable model code and post-processing tool
 #------------------------------------------------------------------------------#
 # Create mppnccombine; should supply with same libraries supplied to model executable through its makefile
 # $pgi/pgcc -O -o $mppnccombine -I$netcdfc/include -I$mpich/include $mppnsource $flags_links $flags_libs
 time=$(date +%s)
 echo "Generating mppnccombine executable..."
-$pgi/pgcc -O -o mppnccombine.x $flags_include $mppnsource $flags_links $flags_libs
-  # -O[level] = set optimization level; sets to 2 if number not specified
-  # -o file = use this file as name of executable
-  # -I directory = add directory to compiler search path; these are 'header' files
-  # -L directory = change the directory in which "linker" searches for libraries
-  # -l library = load lib<library>.a from the standard library directory (supplied by L?)
+$cpp -O -o $execdir/mppnccombine.x $flags_include $flags_links $flags_fort $mppnsource
+
 #------------------------------------------------------------------------------#
 # Build makefile template (assumes pgi bin is on $PATH)
 cd $execdir # move to source directory
 cat > mkmf.template << DELIM
-CC = $pgi/pgcc
-FC = $pgi/pgf90
-LD = $pgi/pgf90
-CPPFLAGS = -Mmpi=mpich
-FFLAGS = -Mmpi=mpich -r8 -Ktrap=fp -pc 64 -O2
-LDFLAGS = $flags_links $flags_libs -Mmpi=mpich
+CC = $cpp
+FC = $fortran
+LD = $fortran
+CPPFLAGS =
+FFLAGS = -r8 -pc 64 $flags_float $flags_optimization
+LDFLAGS = $flags_links $flags_fort $flags_ld
 LIST = -Mlist
 DELIM
 cat $mkmftemplate >> mkmf.template # appends provided template to custom defs
+
 #------------------------------------------------------------------------------#
 # Create makefile
 echo "Generating Makefile..."
 cat mkmf.template
 $mkmf -p fms.x -t mkmf.template -c "$cppdefs" -a $src $pathnames \
   $src/shared/mpp/include $src/shared/include ${include[@]} # the other include files
-  # -p = program (name of final target)
-  # -t = template (list of MACROS/COMMANDS that get appended to beginning of final Makefile)
-  # -c = list of 'cpp #define's passed to source files (what?)
-  # -a = abspath, attaches 'abspath' (here, $src) to the FRONT of RELATIVE paths to the source file
-  # args (all the later stuff) = list of directories/files to be searched for targets and dependencies
+
 #------------------------------------------------------------------------------#
 # Compile source
 echo "Compiling source code..."
diff --git a/drycore_run b/drycore_run
--- a/drycore_run
+++ b/drycore_run
@@ -10,33 +10,27 @@
 # * 8  cores: 10-day  Control  run, T42 64lats was 140  seconds
 # * 12 cores: 10-day  Spindown run, T39 60lats was 111  seconds
 ################################################################################
-# First a couple functions for parsing namelist options
-################################################################################
-function Parse() { # will just print out result; also, trims string quotes, comments, whitespace
-  cat input.nml | sed 's/!.*//g' | grep "$1" | cut -d= -f2 | tr -d "\t ,'\""
-}
-function Replace() { # first argument is param name, second argument is value
-  while [ $# -gt 0 ]; do
-    ! grep '^[ \t]*\b'${1}'\b' input.nml &>/dev/null && \
-      echo "Error: Param \"${1}\" not found in namelist." && exit 1
-    space='\([ \t]*\)' # space atom; more readable to set it as a variable
-    echo "Replacing param \"${1}\" with \"${2}\"."
-    sed -i 's/^'"${space}${1}${space}"'='"${space}"'.*$/\1'${1}'\2=\3'${2}',/g' input.nml
-    shift 2
-    [ $? -ne 0 ] && echo "Error: Must pass even number of params to Replace function."
-  done
-}
-################################################################################
-# Next 
+# Initial stuff 
 ################################################################################
 ulimit -s unlimited # set max open files
 cwd=$(pwd)
+# Compatibility with MPT custom parallel manager on Cheyenne, if you use mpirun
+export MPI_SHEPHERD=true
+# Check that required scripts are available
+fms=$cwd/fms.x       # location of executables
+process=$cwd/process # the script for on-the-fly processing
+case $HOSTNAME in
+  cheyenne*) run=mpiexec_mpt ;; # or mpirun
+  *)         run=mpirun ;;
+esac
+run=mpirun # actually mpiexec_mpt failed immediately
+[ ! -x $fms ]     && echo "Error: The executable $fms is missing."                 && exit 1
+[ ! -x $process ] && echo "Error: The bash script for processing data is missing." && exit 1
 # Declare defaults
 cores=8            # number of cores for parallel
 mode=0             # default is to run the control
 new=false          # do not write to existing experiment directory?
 resume=false       # do not overwrite existing run block?
-days=$(Parse days) # number of days in each block
 # Parse input flags
 # Read the comments to see explanations for each option
 while [ $# -gt 0 ]; do # echo "Flag: $1"
@@ -64,18 +58,31 @@ done
 [[ -z $tstart || -z $tend ]] && echo "Error: Start and end times must be declared." && exit 1
 echo "Keeping full resolution: days ${talldata[@]}"
 
-# Check that required scripts are available
-fms=$cwd/fms.x       # location of executables
-process=$cwd/process # the script for on-the-fly processing
-[ ! -x $fms ]     && echo "Error: The executable $fms is missing."                 && exit 1
-[ ! -x $process ] && echo "Error: The bash script for processing data is missing." && exit 1
-
 # Optionally exit from script if directory already exists
 $new && [ -d $expdir ] && echo "Error: Working directory already exists. Continuing..." && exit 1
 if [ ! -d $expdir ]; then
   mkdir $expdir # make directory
   [ $? -ne 0 ] && echo "Error: Could not create experiment directory \"$expdir\"." && exit 1
 fi
+
+# Helper functions
+function Parse() {
+  # Get namelist value for the *global*, experiment-series namelist
+  cat $expdir/input.nml | sed 's/!.*//g' | grep "$1" | cut -d= -f2 | tr -d "\t ,'\""
+}
+function Replace() { # first argument is param name, second argument is value
+  # Replace namelist value for a *local* spindown experiment
+  while [ $# -gt 0 ]; do
+    ! grep '^[ \t]*\b'${1}'\b' ./input.nml &>/dev/null && \
+      echo "Error: Param \"${1}\" not found in namelist." && exit 1
+    space='\([ \t]*\)' # space atom; more readable to set it as a variable
+    echo "Replacing param \"${1}\" with \"${2}\"."
+    sed -i 's/^'"${space}${1}${space}"'='"${space}"'.*$/\1'${1}'\2=\3'${2}',/g' ./input.nml
+    shift 2
+    [ $? -ne 0 ] && echo "Error: Must pass even number of params to Replace function."
+  done
+}
+days=$(Parse days) # number of days in each block
 
 ################################################################################
 # Helper functions for model runs
@@ -121,14 +128,14 @@ function Setup() {
   # Copy existing namelist file over
   # For shutdown experiments, can edit on the fly to turn off
   # radiation, et cetera, but this is starting point
-  [ ! -r "../input.nml" ]  && echo "Error: input.nml file not found."  && exit 1
-  [ ! -r "../diag_table" ] && echo "Error: diag_table file not found." && exit 1
-  cp ../input.nml  ./
-  cp ../diag_table ./
+  [ ! -r "$expdir/input.nml" ]  && echo "Error: input.nml file not found."  && exit 1
+  [ ! -r "$expdir/diag_table" ] && echo "Error: diag_table file not found." && exit 1
+  cp $expdir/input.nml  ./
+  cp $expdir/diag_table ./
   topo=$(Parse "topography_option") # use helper function
   if [ "$topo" == "input" ]; then
-    [ ! -r ../topography.data.nc ] && echo "Error: Topography file not available." && exit 1
-    cp ../topography.data.nc ./
+    [ ! -r $expdir/topography.data.nc ] && echo "Error: Topography file not available." && exit 1
+    cp $expdir/topography.data.nc ./
   fi
   #----------------------------------------------------------------------------#
   # Change namelist properties
@@ -159,13 +166,13 @@ function Run() {
   # taskset -cp 0-19 $! 1>/dev/null # $! == pid of last job run in background
   # Note mpirun must be on path
   ! which mpirun &>/dev/null && echo "Error: mpirun not found in \$PATH." && exit 1
-  mpirun -np $cores ./fms.x &>log.model # need ./fms.x, not fms
+  $run -np $cores ./fms.x &>log.model # need ./fms.x, not fms
   # Check that model ran successfully
   # FMS prints to standard output 'EXIT CODE: 1' but doesn't actually set
   # the exit code/mpirun doesn't pass that exit code, which is fucking dumb.
   # Instead parse the logfile
   grep 'EXIT CODE: [1-9]' log.model &>/dev/null && \
-    echo "Error: Bad exit code from model run step..." && exit 1
+    echo "Error: Bad exit code from model run step." && exit 1
   # Wait for previous processing step, if set
   # If unset, means we are just now starting the model runs
   if [ ! -z $pp ]; then # post-processing is active
@@ -173,7 +180,7 @@ function Run() {
     if [ $estatus != 0 ]; then
       echo "Error: Exit status $estatus from post-processing previous block..."
       case $estatus in
-        1) echo "Something failed during model integration. Check log.model." ;;
+        1) echo "NetCDF files missing. Check log.model." ;;
         2) echo "Something failed during model interpolation. Check log.interp." ;;
         3) echo "Something failed while getting basic terms. Check log.basic." ;;
         4) echo "Something failed while getting Lorenz cycle terms. Check log.lorenz." ;;
@@ -237,7 +244,7 @@ estatus=0
 case $mode in
   0) # CHECK THAT TIMING VARIABLES ARE DECLARED
   # PREPARE FOR THE LOOP
-  echo "Running control experiment from day $tstart to day $tend."
+  echo "Running control experiment from day $tstart to day $tend, restart every $days days."
   coldstart=true # assume cold start by default
   origin=$(date +%s) # start time
   pday=$(($tstart - $days)) # only time when we do minus days
@@ -292,7 +299,7 @@ case $mode in
   ;; *) # CHECK THAT TIMING VARIABLES ARE DECLARED
   [ -z $tspindown ] && echo "Error: Must declare starting times for spindown experiments." && exit 1
   # PREPARE FOR THE LOOP
-  echo "Running spindown experiment $mode from days ${tspindown[@]} for $tend days."
+  echo "Running spindown experiment $mode from days ${tspindown[@]} for $tend days, restart every $days days."
   origin=$(date +%s)
   # ITERATE THROUGH STARTING DAYS
   for eday in "${tspindown[@]}"; do
diff --git a/drycore_series b/drycore_series
--- a/drycore_series
+++ b/drycore_series
@@ -34,25 +34,26 @@
 #     corresponding roughly to Held-Suarez standard) the sweep will be renamed
 #     to 'base', and the directory will be named force_*base*_resolution.
 ################################################################################
-# Tasks to run
-dryrun=false # just print function calls
-testmode=0 # 0 is no test, 1 is run for a day or two, 2 is check initial output
-runmode=0  # 0 is control run, the rest are different spindown modes:
-  # 1 for radiation off, 2 for radiation off but surface on, 
-  # 3 for everything off (radiation, surface, and friction), 4 for friction off
-# Model run settings
-new=false # do not write to existing experiment directories?
-resume=false # do not overwrite existing dXXXX-dYYYY directories?
-
-# Parse input
+# Default settings
+# For runmode: 0 is control run, the rest are different spindown modes:
+# 1 for radiation off, 2 for radiation off but surface on, 
+# 3 for everything off (radiation, surface, and friction), 4 for friction off
+# For testmode: 0 is normal, 1 is quick test, 2 is spit out the
+# initial conditions (i.e. forcing environment)
+runmode=0
 testmode=0
+dryrun=false # just print function calls
+resume=false # do not overwrite existing dXXXX-dYYYY directories?
+new=false # do not write to existing experiment directories?
+# Parse input
 unset series
 while [ $# -gt 0 ]; do # echo "Flag: $1"
   case "$1" in
-    --test)  testmode=1 ;;
+    --test) testmode=1 ;;
     --init) testmode=2 ;;
     --1=*) params1=($(echo ${1#*=} | tr ',' ' ')) ;;
     --2=*) params2=($(echo ${1#*=} | tr ',' ' ')) ;;
+    --mode=*) runmode=${1#*=} ;;
     -*) echo "Error: Unknown flag \"$1\"." && exit 1 ;;
     *) [ -n "$series" ] && echo "Error: More than one experiment series specified." && exit 1
        series="$1" ;;
@@ -70,7 +71,6 @@ reso="${reso%%_*}"
 
 # Next parameter sweeps and timing
 cores=8 # default core count
-rdays=d1100-d1200 # set restart directory days (leave empty to just use the last subfolder in directory)
 case $testmode in 0)
   filename=4xdaily_inst # name for output files
   frequnits=hours       # hours
@@ -87,11 +87,12 @@ case $testmode in 0)
 # Run really fast test run
 ;; 1)
   filename=test
-  cores=1
+  cores=16
   extra="--no-move " # pass to process script; don't move/delete anything
-  rdir="${force}_base_t42l40s" # override previous directory
-  dt=600 days=1 secs=0 outfreq=1 frequnits=hours
-  tstart=0 tend=3 tspindown=3
+  # rdir="${force}_base_t42l40s" # override previous directory
+  # rdays=d1100-d1200 # set restart directory days (leave empty to just use the last subfolder in directory)
+  dt=600 days=10 secs=0 outfreq=1 frequnits=hours
+  tstart=0 tend=10 tspindown=3
   new=false resume=false
 # Initial conditions
 ;; 2)
@@ -105,6 +106,36 @@ case $testmode in 0)
 ;; esac
 
 #------------------------------------------------------------------------------#
+# Paths
+#------------------------------------------------------------------------------#
+# Storage information for runscript and post-processing script
+storage=$HOME
+scratch=$HOME # on Euclid, home is unmounted/not backed up; so disk I/O is quick
+f90dir=$HOME/gfdl-drycore # model code folder
+bindir=./drycore-${HOSTNAME%%.*} # compiled model code folder (should be in this folder)
+case ${HOSTNAME%%.*} in
+  # olbers)
+  #   scratch=''
+  # ;; gauss)
+  #   scratch=/birner-scratch/ldavis # need to use special scratch directory
+  euclid)
+    storage=/birner-home/ldavis # this directory is backed up; synced with GAUSS home folder
+  ;; monde)
+    scratch=/mdata1/ldavis
+  ;; cheyenne*)
+    storage=/glade/u/home/davislu
+    scratch=/glade/scratch/davislu # https://www2.cisl.ucar.edu/resources/storage-and-file-systems/glade-file-spaces
+    bindir=drycore-cheyenne
+  ;; *) echo "Error: Unknown host, must edit batch script before continuing." && exit 1 ;;
+esac
+[ ! -d "$storage/data" ] && { mkdir "$storage/data"; echo "Created storage directory."; }
+# Copy over the appropriate executable file
+cp $bindir/fms.x ./ # location of executables
+[ $? -ne 0 ] && echo "Error: fms.x not found in \"$bindir\"." && exit 1
+cp $bindir/mppnccombine.x ./ # location of executables
+[ $? -ne 0 ] && echo "Error: mppnccombine.x not found in \"$bindir\"." && exit 1
+
+#------------------------------------------------------------------------------#
 # Helper function
 #------------------------------------------------------------------------------#
 # Call this function as Add param v<value> param v<value>
@@ -113,7 +144,7 @@ case $testmode in 0)
 #   series does not change that value), will not add to arrays
 # * Function accounts for situation when you pass an empty string parameter
 #   or negative number, and have weird strings like "v-" and "v''"
-function Add() {
+function ArrayAdd() {
   while [ $# -ne 0 ]; do
     if [ -n "$2" ] && [ "${#2}" -gt 1 ] && [ "$2" != "v-" ] && [ "$2" != "v''" ]; then
       [ "${2:0:1}" != v ] && echo "Error: Values must be input as v<value>." && exit 1
@@ -125,43 +156,11 @@ function Add() {
 }
 
 #------------------------------------------------------------------------------#
-# Paths
-#------------------------------------------------------------------------------#
-# Storage information for runscript and post-processing script
-storage=/home/ldavis
-scratch=/home/ldavis # on Euclid, home is unmounted/not backed up; so disk I/O is quick
-case ${HOSTNAME%%.*} in
-  olbers)
-    mpibin=/usr/local/mpich3/bin
-    ;;
-  gauss)
-    mpibin=/usr/local/mpich3-pgi/bin
-    scratch=/birner-scratch/ldavis # need to use special scratch directory
-    ;;
-  euclid)
-    mpibin=/usr/local/bin
-    storage=/birner-home/ldavis # this directory is backed up; synced with GAUSS home folder
-    ;;
-  monde)
-    mpibin=/usr/lib64/mpich/bin
-    scratch=/mdata1/ldavis
-    ;;
-  *) echo "Error: Unknown host, must edit batch script before continuing." && exit 1 ;;
-esac
-PATH="$mpibin:$PATH" # will *not* be exported to invoking shell; so this is nbd
-[ ! -d "$storage/data" ] && { mkdir "$storage/data"; echo "Created storage directory."; }
-# Copy over the appropriate executable file
-execdir=${HOSTNAME%%.*}
-cp $execdir/fms.x ./ # location of executables
-[ $? -ne 0 ] && echo "Error: fms.x not found in \"$execdir\"." && exit 1
-cp $execdir/mppnccombine.x ./ # location of executables
-[ $? -ne 0 ] && echo "Error: mppnccombine.x not found in \"$execdir\"." && exit 1
-
-#------------------------------------------------------------------------------#
 # Run multiple experiments consecutively
 #------------------------------------------------------------------------------#
 # Setup
 echo
+echo "Forcing: $force, Sweep: $sweep, Resolution: $reso"
 exps=() # record completed experiments
 cwd=$(pwd)
 counter=0
@@ -340,12 +339,12 @@ for param1 in ${params1[@]}; do
       # Add parameters to lists
       #----------------------------------------------------------------------------#
       # Forcing settings
-      Add delh v$delh
-      Add strat_mode v\'$force\' strat_damp v\'$stratdamp\'
-      Add ktrop v$ktrop kfric v$kfric kbl v$kbl kstrat v$kstrat kmeso v$kmeso z_kdepth v$kdepth
+      ArrayAdd delh v$delh
+      ArrayAdd strat_mode v\'$force\' strat_damp v\'$stratdamp\'
+      ArrayAdd ktrop v$ktrop kfric v$kfric kbl v$kbl kstrat v$kstrat kmeso v$kmeso z_kdepth v$kdepth
       # Timing variables
       # These ones are not experiment dependent so far, and are *global*
-      Add dt_atmos v$dt days v$days seconds v$secs
+      ArrayAdd dt_atmos v$dt days v$days seconds v$secs
       # Set horizontal coordinates
       ntrunc=${reso%l*}
       ntrunc=${ntrunc#t}
@@ -359,7 +358,7 @@ for param1 in ${params1[@]}; do
       esac
       nsphere=$(($ntrunc + 1)) # forget what difference between num fourier and num spherical means
       nlon=$(($nlat * 2)) # always twice the res
-      Add num_fourier v$ntrunc num_spherical v$nsphere lat_max v$nlat lon_max v$nlon
+      ArrayAdd num_fourier v$ntrunc num_spherical v$nsphere lat_max v$nlat lon_max v$nlon
       # Now vertical resolution options
       # Will raise error if string-specifier is unknown
       vert=${reso#*l}
@@ -370,10 +369,10 @@ for param1 in ${params1[@]}; do
         *s) coord=even_sigma; nlev=${vert%s}; levels=               ;; # ERA-Interim coordinates
         *) echo "Error: Unknown vertical coordinate identifier \"${vert}\"."; exit 1; ;;
       esac
-      Add num_levels v$nlev vert_coord_option v\'$coord\'
+      ArrayAdd num_levels v$nlev vert_coord_option v\'$coord\'
 
       #----------------------------------------------------------------------------#
-      # Apply modifications to namelist
+      # Add 'params' keys with 'values' values to namelist
       #----------------------------------------------------------------------------#
       # Message
       echo "Updating namelist with:"
@@ -384,10 +383,11 @@ for param1 in ${params1[@]}; do
       printf "$message" | column -t
       # Copy over the default namelist
       nml=$expdir/input.nml
-      nml_default=./input_default.nml
+      nml_default=$f90dir/input_default.nml
+      echo "Copy $nml_default to $nml"
       cp $nml_default $nml # move over defaut
       # Add forcing namelist
-      nml_forcing=forcing_default.nml
+      nml_forcing=$f90dir/forcing_default.nml
       [ ! -r "$nml_forcing" ] && echo "Error: File \"$nml_forcing\" not found." && exit 1
       cat $nml_forcing >>$nml # append that shit
       # Add coordinate namelist, potentially
@@ -400,12 +400,14 @@ for param1 in ${params1[@]}; do
       # timing variables. For others, just change in the namelist file directly.
       [ ${#params[@]} -ne ${#values[@]} ] && echo "Error: One of the batch script namelist params is unset." && exit 1
       for i in $(seq 0 $((${#params[@]}-1))); do
+        # echo param $param, value $value, namelist $nml
         param=${params[$i]}
         value=${values[$i]}
         [ -z "$param" ] && continue # e.g. stratosphere timescale should be empty
         ! grep '^[ \t]*\b'${param}'\b' $nml &>/dev/null && \
           echo "Error: Param \"${param}\" not found in namelist." && exit 1
         space='\([ \t]*\)' # space atom; more readable to set it as a variable
+        sed -i 's/^'"${space}${param}${space}"'='"${space}"'.*$/\1'${param}'\2=\3'${value}',/g' $nml
         sed -i 's/^'"${space}${param}${space}"'='"${space}"'.*$/\1'${param}'\2=\3'${value}',/g' $nml
       done
       # Remove comments to be safe
@@ -432,7 +434,7 @@ for param1 in ${params1[@]}; do
       [ ! -z "$talldata" ]  && flags+="--days-alldata=$talldata " # keep XYZ data
       [ ! -z "$tnodata" ]   && flags+="--days-nodata=$tnodata " # record zero data
       [ ! -z "$tspindown" ] && flags+="--days-spindown=$tspindown " # record zero data
-      # Run experiment
+      # Run experiment (or just echo command for dryrun)
       $dryrun && cmd="echo ./drycore_run" || cmd="./drycore_run"
       $cmd $expdir $flags --mode=$runmode --start=$tstart --end=$tend --cores=$cores --extra="$extra" # could be empty string
       [ $? -ne 0 ] && echo "Warning: $exp integration failed." && echo && echo && echo && continue # keyboard interruption does not trigger this
diff --git a/process b/process
--- a/process
+++ b/process
@@ -22,6 +22,11 @@ function nclcheck() { # input log file as argument
   return $? # return exit code; good status means we found error, bad status means we found nothing
     # ignore ^warning: because these will also happen if we have a systemfunc error possibly
 }
+
+# Make sure modules loaded
+module load ncl &>/dev/null
+module load cdo/1.9.4 &>/dev/null
+
 # Parse input flags
 nomove=false      # keep data in original folder, instead of moving to ../netcdf? useful for testing
 keepxyz=false     # keep original "full" results?
@@ -36,10 +41,11 @@ while [ $# -gt 0 ]; do
     -m|--no-move)      nomove=true      ;; # if true, keep all intermediate files
     -i|--interp-cdo)   cdointerp=false  ;; # interpolate with CDO instead of NCL? much slower during testing (see notes)
     -c|--combine-only) onlycombine=true ;; # only combine data
-    *) echo "Error: Unknown flag \"$1\"." && exit 1 ;;
+    *) echo "Error: Unknown flag \"$1\"." && exit 127 ;;
   esac
   shift # shift by one
 done
+
 # Global vars
 t0=$(date +%s)                    # starting time
 bin=${0%/*}                       # same location as this file; trim filename from right
@@ -49,7 +55,6 @@ mppnccombine=$bin/mppnccombine.x  # combine; needs to have been compiled here
 params=$bin/process_params.ncl    # params with NCL
 basics=$bin/process_basic         # zonal means and flux terms with CDO
 lorenz=$bin/process_energy.ncl    # eddy and mean Lorenz energy cycle terms with NCL
-process3d=$bin/process_3d         # 3d processing with CDO and stuff
 # lorenz=$bin/process_lorenz      # Lorenz energy cycle terms with CDO
 # energy=$bin/process_energy      # Lorenz energy cycle terms with CDO
 # Double check some stuff
@@ -65,27 +70,36 @@ process3d=$bin/process_3d         # 3d processing with CDO and stuff
 # Combine the files produced in parallel
 # And check if any netCDF output; see: https://stackoverflow.com/q/2937407/4970632
 if $resume; then
-  # Will use existing _full.nc XYZ resolution files for getting the XY files
+  # Will use existing _full.nc XYZ resolution files for getting the YZ files
   echo "Using previous model results for getting XY files."
   if $nomove; then
     ncfiles=(*_full.nc)
   else
     ncfiles=(../netcdf/*_full.${PWD##*/}.nc)
   fi
-  [[ "$ncfiles" =~ "*" ]] && echo "Error: XYZ resolution file was not found."
+  [[ "$ncfiles" =~ "*" ]] && echo "Error: XYZ resolution files not found." && exit 1
 else
-  # Will process the raw model output, then get the _full XYZ files and XY files from result
+  # Merge files produced in parallel, then get the _full XYZ files and YZ files from result
   t=$(date +%s)
-  for ncfile in *.nc.0000; do # for each output filename
-    [[ "$ncfile" =~ "*" ]] && echo "Error: No netcdf files found." && exit 1 # make sure nullglob turned off
-    files=(${ncfile%%.*}.nc*) # put into array
-    echo "Combining files: ${files[@]} into ${ncfile%%.*}.nc"
-    $mppnccombine -r ${ncfile%%.*}.nc ${files[@]}
-  done # -r flag says to remove the decomposed .0000 files after they are combined; arg 1 is output, arg 2-N is input
+  ncfiles=(*.nc.0000)
+  if [[ "$ncfiles" =~ "*" ]]; then
+    ncfiles=(*.nc) # already present?
+    if [ ${#ncfiles[@]} -ge 1 ]; then
+      echo "Note: Model ran on only 1 core, do not need to merge files."
+    else
+      echo "Error: Model output files not found." && exit 1 # make sure nullglob turned off
+    fi
+  else
+    for ncfile in *.nc.0000; do # for each output filename
+      files=(${ncfile%%.*}.nc*) # put into array
+      echo "Combining files: ${files[@]} into ${ncfile%%.*}.nc"
+      $mppnccombine -r ${ncfile%%.*}.nc ${files[@]}
+    done # -r flag says to remove the decomposed .0000 files after they are combined; arg 1 is output, arg 2-N is input
+    ncfiles=(*.nc) # each output file
+  fi
   echo "  * Time for combining files: $(($(date +%s) - $t))s."
   # Initialize directory for output
   [ ! -d ../netcdf ] && mkdir ../netcdf # make directory if doesn't exist
-  ncfiles=(*.nc) # each output file
 fi
 # Optional exit, if only wanted to combine data
 if $onlycombine; then
@@ -119,6 +133,7 @@ for ncfile in ${ncfiles[@]}; do
   ncatted -O -a long_name,udamp,o,c,"Rayleigh damping of zonal wind" $ncfile
   ncatted -O -a long_name,vdamp,o,c,"Rayleigh damping of meridional wind" $ncfile
 
+
   ############################################################################
   if ! $resume; then # data already interpolated
     # 1) Interpolate the data to pressure levels
@@ -147,7 +162,6 @@ for ncfile in ${ncfiles[@]}; do
     $nomove && ncfile=$interpfile || mv $interpfile $ncfile # move old file on top of new file
     echo "  * Time for interpolation: $(($(date +%s) - $t))s."
   fi
-
   # ##############################################################################
   # # Add some parameters to the longitude-latitude file with NCL
   # t=$(date +%s)
@@ -167,8 +181,9 @@ for ncfile in ${ncfiles[@]}; do
   pbasics=$!
   # [ $? != 0 ] && echo "Error: Something failed while getting basic terms." && exit 3
   # echo "  * Time for getting basic terms with CDO: $(($(date +%s) - $t))s."
+
   ##############################################################################
-  # Next the NCL commands; used to get energy terms
+  # 3) The NCL commands; used to get energy terms
   # Some of these require the extra variables output by NCL; also meridional flux
   # terms rely on NCL having set poleward==positive in each hemisphere
   # t=$(date +%s)
@@ -179,6 +194,7 @@ for ncfile in ${ncfiles[@]}; do
   #   echo "Error: Something failed getting extra parameters with NCL." && exit 4
   # fi
   # echo "  * Time for getting Lorenz energy terms with NCL: $(($(date +%s) - $t))s."
+
   ##############################################################################
   # Manage the two background processes
   wait $pbasics # wait for basic terms
@@ -214,7 +230,7 @@ for ncfile in ${ncfiles[@]}; do
       t=$(date +%s)
       echo "Keeping XYZ file and calculating extra terms..."
       cdo -O -s -uv2dv -selname,u,v $ncfile dv0.nc 1>/dev/null          # gets spectral coefs for vor/div from Gaussian grid of u/v
-      cdo -O -s -delname,velopot -invertlat -sp2gp -dv2ps dv0.nc dv1.nc # spectral vor/div to spectral streamfunc/velocity pot; throw out the latter
+      cdo -O -s -delname,velopot       -invertlat -sp2gp -dv2ps dv0.nc dv1.nc # spectral vor/div to spectral streamfunc/velocity pot; throw out the latter
       cdo -O -s -chname,sd,div,svo,vor -invertlat -sp2gp dv0.nc dv2.nc  # better names
       ncap2 -O -s '*f[$lat] = 2*7.292e-5*sin(lat*3.14159/180); absvor = vor+f' dv2.nc dv2.nc # tack on absolute vorticity
         # get absolute vorticity; asterisk means this is a "RAM" variable, not saved in final output
@@ -234,28 +250,8 @@ for ncfile in ${ncfiles[@]}; do
     fi
   fi
 done
+
 # Finally, echo time of finish
 # Can parse this to send message to the window that ran the runscript/batch runscript
 # echo $(($(date +%s) - $t0)) # prints UNIX time difference
 echo "TOTAL TIME ELAPSED: $(($(date +%s) - $t0))s."
-
-################################################################################
-# Old stuff
-# Previous CDO commands
-# cdo $flags chname,f0,EHF -zonmean $timmean \
-#   -mul -selvar,f0 $ncfile \
-#        -div -mul -sub -selvar,pt $ncfile -enlarge,$ncfile -zonmean -selvar,pt $ncfile \
-#                  -sub -selvar,v $ncfile -enlarge,$ncfile -zonmean -selvar,v $ncfile \
-#             -selvar,dthdp $ncfile \
-# cdo $flags chname,u,KE $timmean \
-#   -add -divc,9.81 -divc,2 -add -sqr -selvar,u out1.nc \
-#                                -sqr -selvar,v out1.nc \
-#        -selvar,EKE out5.nc \
-#   out7.nc # the total kinetic energy
-# Whitespace-safe option for looping through glob results:
-# find . -iname "*.nc.0000" | while read ncfile; do
-# find . -iname "*.nc" | while read file; do
-# Note: 'read' reads each line from standard input and splits line into variable names
-# requested (e.g. could have read a b c <<< "foo bar baz"); the while works because exit
-# status is 1 during read process, and is 0 when reaching end of file/data stream
-
