Fixes

diff --git a/process_repair b/process_repair
--- a/process_repair
+++ b/process_repair
@@ -1,8 +1,12 @@
 #!/usr/bin/env bash
 # Iterate through a bunch of glob patterns
 # in the scratch directory
+# shopt -s nullglob
 repair=./process_repair.ncl
-nclcheck() { cat $1 | grep -v "Execute.c" | grep -v "systemfunc" | egrep "^fatal:" &>/dev/null; }
+nclcheck() {
+  cat $1 | grep -v "Execute.c" | grep -v "systemfunc" | egrep "^fatal:" &>/dev/null
+  return $? # is *zero* if we *found error strings*
+}
 case ${HOSTNAME%%.*} in
   monde)
     scratch=/mdata1/ldavis
@@ -11,18 +15,18 @@ case ${HOSTNAME%%.*} in
   ;; *) echo "Error: Unknown host, must edit batch script before continuing." && exit 1 ;;
 esac
 # Loop
-globs=('hs_troprad3_t95l60e*')
+globs=('hs_troprad3_t95l60e*1000*' 'hs_tgrad_t95l60e*')
 for glob in "${globs[@]}"; do
-  for dir in $glob; do
+  for dir in $scratch/$glob; do
     echo "Dir: ${dir##*/}"
-    sleep 5
-    filenames=($dir/netcdf/*summary*.nc)
+    filenames=($dir/netcdf/*summary.d????-d????.nc)
     for filename in ${filenames[@]}; do
-      echo "File: $filename"
-      output=${filename%.nc}_tmp.nc # try again
-      ncl -n -Q "filename=\"$filename\"" "output=\"$output\"" $repair &>log.fix #2> /dev/null
+      echo "File: ${filename##*/}"
+      # output=${filename%.nc}_tmp.nc # try again
+      # [ -r $output ] && rm $output
+      ncl -n -Q "filename=\"$filename\"" $repair 2>&1 | tee log.fix #2> /dev/null
       nclcheck log.fix
-      sleep 3
+      [ $? -eq 0 ] && echo "Error: Failed." && exit 1
     done
   done
 done
