Logs, minor changes, cleanup

diff --git a/process_parallel b/process_parallel
--- a/process_parallel
+++ b/process_parallel
@@ -43,24 +43,21 @@ while [ $# -gt 0 ]; do
   esac
   shift # shift by one
 done
-debug=false # test
-keepxyz=true
 
 # Global vars
 t0=$(date +%s) # starting time
 bin=${0%/*}    # same location as this file; trim filename from right
 run=mpirun     # for running mppnccombine on Cheyenne; parallelization really necessary
-interpcdo=$bin/process/process_interp.cdo # interpolate with CDO
-interpncl=$bin/process/process_interp.ncl # interpolate with NCL, automatic iteration
+interp_cdo=$bin/process_interp.cdo # interpolate with CDO
+interp_ncl=$bin/process_interp.ncl # interpolate with NCL, automatic iteration
 mppnccombine=$bin/mppnccombine.x          # combine; needs to have been compiled here
-basics=$bin/process/process_basics.cdo    # zonal means and flux terms with CDO
-lorenz=$bin/process/process_energy.ncl    # eddy and mean Lorenz energy cycle terms with NCL
-# energy=$bin/process_energy      # energy cycle terms with CDO
+process_cdo=$bin/process_params.cdo    # zonal means and flux terms with CDO
+process_ncl=$bin/process_params.ncl    # eddy and mean Lorenz energy cycle terms with NCL
 
 # Double check some stuff
-[ ! -x $basics ]        && echo "Error: The script \"$basics\" is missing."                       && exit 127
-[ ! -x $lorenz ]        && echo "Error: The script \"$lorenz\" is missing."                       && exit 127
-[ ! -r $interpncl ]     && echo "Error: The script \"$interpncl\" is missing."                    && exit 127
+[ ! -x $process_cdo ]        && echo "Error: The script \"$process_cdo\" is missing."                       && exit 127
+[ ! -r $process_ncl ]        && echo "Error: The script \"$process_ncl\" is missing."                       && exit 127
+[ ! -r $interp_ncl ]     && echo "Error: The script \"$interp_ncl\" is missing."                    && exit 127
 [ ! -x $mppnccombine ]  && echo "Error: The mpp combine executable \"$mppnccombine\" is missing." && exit 127
 ! hash ncl 2>/dev/null  && echo "Error: NCL is not in $PATH."                                     && exit 127
 ! hash cdo 2>/dev/null  && echo "Error: CDO is not in $PATH."                                     && exit 127
@@ -90,13 +87,13 @@ hybrid_to_press() {
   # a) Use CDO for interpolation
   if $cdointerp; then
     echo "Interpolating with CDO..."
-    $interpcdo $ncfile $output &>LOGS/log.interp.${suffix%.nc} # that simple babe
+    $interp_cdo $ncfile $output &>LOGS/log.interp.${suffix%.nc} # that simple babe
     [ $? != 0 ] && echo "Error: Something failed during CDO interpolation." && exit $?
     ! $debug && rm interp?.$suffix
   # b) Use NCL vint2hp_ecmwf for interpolation
   else
     echo "Interpolating with NCL..." # -Q = no banner, -n = do not enumerate print statements
-    ncl -n -Q "filename=\"$ncfile\"" "outfile=\"$output\"" $interpncl &>LOGS/log.interp.${suffix%.nc} #2> /dev/null
+    ncl -n -Q "filename=\"$ncfile\"" "outfile=\"$output\"" $interp_ncl &>LOGS/log.interp.${suffix%.nc} #2> /dev/null
     if nclcheck LOGS/log.interp.${suffix%.nc} || [ ! -r $output ]; then
       echo "Error: Something failed during NCL interpolation." && exit 2
     fi
@@ -135,7 +132,7 @@ yz_params() {
   # Fluxes and means
   t=$(date +%s)
   echo "Getting CDO YZ parameters..."
-  $basics $ncfile $suffix &>LOGS/log.basic.${suffix%.nc} #&
+  $process_cdo $ncfile $suffix &>LOGS/log.basic.${suffix%.nc} #&
   [ $? != 0 ] && echo "Error: Something failed while getting CDO parameters." && exit 3
   t2=$(($(date +%s) - t))
   # t2=$(tail -1 LOGS/log.basic.${suffix%.nc} | sed 's/[^0-9]*//g')
@@ -146,7 +143,7 @@ yz_params() {
   # terms rely on NCL having set poleward==positive in each hemisphere
   t=$(date +%s)
   echo "Getting NCL YZ parameters..."
-  ncl -n -Q "suffix=\"$suffix\"" "filename=\"$ncfile\"" $lorenz &>LOGS/log.lorenz.${suffix%.nc} #&
+  ncl -n -Q "suffix=\"$suffix\"" "filename=\"$ncfile\"" $process_ncl &>LOGS/log.lorenz.${suffix%.nc} #&
   if nclcheck LOGS/log.lorenz.${suffix%.nc}; then
     echo "Error: Something failed while getting NCL parameters." && exit 4
   fi
@@ -219,8 +216,9 @@ for file in ${files[@]}; do
     base=${file%%.*}
     for part in ${base}.nc*; do
       num=${part##*.}
-      mv $part ${base}.${num}.nc # some programs won't recognize file without .nc extension
+      mv $part ${base}.${num}.nc & # some programs won't recognize file without .nc extension
     done
+    wait # in background
     parts=(${base}.*.nc)
   else
     combine=false
@@ -278,8 +276,16 @@ for file in ${files[@]}; do
       ! $debug && rm ${parts[@]} # simple
     else
       # Merge XYZ files
+      # Will drop variables in parallel before merging
+      # NOTE: Might also consider dropping some timesteps, but currently
+      # already only doing 12 hourly data
       t=$(date +%s)
       echo "Keeping XYZ files..."
+      for ncfile in ${parts[@]}; do
+         # ncks -O -d time,1,,2 -x -v omega,udt,vdt,tdt $ncfile $ncfile &
+         ncks -O -v omega,udt,vdt,tdt $ncfile $ncfile &
+      done
+      wait
       $mppnccombine -r $xyzfile ${parts[@]}
       echo "  * Time for combining XYZ files: $(($(date +%s) - t))s."
     fi
